//
// auto-generated by ops.py
//
#include "./OpenACC/opensbli_common.h"
#include <math.h>
#include "ops_macros.h"
#include <openacc.h>

//user kernel files
#include "opensbliblock00Kernel034_openacc_kernel_c.c"
#include "opensbliblock00Kernel037_openacc_kernel_c.c"
#include "opensbliblock00Kernel038_openacc_kernel_c.c"
#include "opensbliblock00Kernel039_openacc_kernel_c.c"
#include "opensbliblock00Kernel040_openacc_kernel_c.c"
#include "opensbliblock00Kernel041_openacc_kernel_c.c"
#include "opensbliblock00Kernel046_openacc_kernel_c.c"
#include "opensbliblock00Kernel030_openacc_kernel_c.c"
#include "opensbliblock00Kernel031_openacc_kernel_c.c"
#include "opensbliblock00Kernel032_openacc_kernel_c.c"
#include "opensbliblock00Kernel033_openacc_kernel_c.c"
#include "opensbliblock00Kernel001_openacc_kernel_c.c"
#include "opensbliblock00Kernel003_openacc_kernel_c.c"
#include "opensbliblock00Kernel014_openacc_kernel_c.c"
#include "opensbliblock00Kernel016_openacc_kernel_c.c"
#include "opensbliblock00Kernel019_openacc_kernel_c.c"
#include "opensbliblock00Kernel007_openacc_kernel_c.c"
#include "opensbliblock00Kernel024_openacc_kernel_c.c"
#include "opensbliblock00Kernel000_openacc_kernel_c.c"
#include "opensbliblock00Kernel002_openacc_kernel_c.c"
#include "opensbliblock00Kernel004_openacc_kernel_c.c"
#include "opensbliblock00Kernel006_openacc_kernel_c.c"
#include "opensbliblock00Kernel008_openacc_kernel_c.c"
#include "opensbliblock00Kernel009_openacc_kernel_c.c"
#include "opensbliblock00Kernel010_openacc_kernel_c.c"
#include "opensbliblock00Kernel011_openacc_kernel_c.c"
#include "opensbliblock00Kernel028_openacc_kernel_c.c"
#include "opensbliblock00Kernel029_openacc_kernel_c.c"
#include "opensbliblock00Kernel047_openacc_kernel_c.c"
