//
// auto-generated by ops.py
//

int xdim0_opensbliblock00Kernel034;
int xdim1_opensbliblock00Kernel034;
int xdim2_opensbliblock00Kernel034;
int xdim3_opensbliblock00Kernel034;
int xdim4_opensbliblock00Kernel034;
int xdim5_opensbliblock00Kernel034;


//user function



void opensbliblock00Kernel034_c_wrapper(
  double * restrict rhoE_B0_p,
  double * restrict rho_B0_p,
  double * restrict rhou0_B0_p,
  double * restrict rhou1_B0_p,
  double * restrict x0_B0_p,
  double * restrict x1_B0_p,
  int * restrict idx,
  int arg_idx0, int arg_idx1,
  int x_size, int y_size) {
  #pragma omp parallel for
  for ( int n_y=0; n_y<y_size; n_y++ ){
    for ( int n_x=0; n_x<x_size; n_x++ ){
      int idx[] = {arg_idx0+n_x, arg_idx1+n_y};
      ptr_double rhoE_B0 = { rhoE_B0_p + n_x*1 + n_y * xdim0_opensbliblock00Kernel034*1, xdim0_opensbliblock00Kernel034};
      ptr_double rho_B0 = { rho_B0_p + n_x*1 + n_y * xdim1_opensbliblock00Kernel034*1, xdim1_opensbliblock00Kernel034};
      ptr_double rhou0_B0 = { rhou0_B0_p + n_x*1 + n_y * xdim2_opensbliblock00Kernel034*1, xdim2_opensbliblock00Kernel034};
      ptr_double rhou1_B0 = { rhou1_B0_p + n_x*1 + n_y * xdim3_opensbliblock00Kernel034*1, xdim3_opensbliblock00Kernel034};
      ptr_double x0_B0 = { x0_B0_p + n_x*1 + n_y * xdim4_opensbliblock00Kernel034*1, xdim4_opensbliblock00Kernel034};
      ptr_double x1_B0 = { x1_B0_p + n_x*1 + n_y * xdim5_opensbliblock00Kernel034*1, xdim5_opensbliblock00Kernel034};
      
   double T = 0.0;
   double Twalld = 0.0;
   double rho = 0.0;
   double rhou0 = 0.0;
   double rhou1 = 0.0;
   OPS_ACC(x0_B0, 0,0) = Delta0block0*idx[0];

   OPS_ACC(x1_B0, 0,0) = Lx1*sinh(by*invLx1*Delta1block0*idx[1])/sinh(by);

   Twalld = Twall;

   T = pref*invRhat/rho;

    rhou0 = ((OPS_ACC(x1_B0, 0,0) < 0.000554055405540554) ? (
   0.0151291766846909 + 7.02589781233594e+113*pow(OPS_ACC(x1_B0, 0,0), 32) +
      2708641767.3071*(OPS_ACC(x1_B0, 0,0)*OPS_ACC(x1_B0, 0,0)) + 6.07590715992659e+87*pow(OPS_ACC(x1_B0, 0,0), 24) +
      7.26086853694613e+139*pow(OPS_ACC(x1_B0, 0,0), 40) + 2.50136219838398e+71*pow(OPS_ACC(x1_B0, 0,0), 19) +
      1.01218895170578e+117*pow(OPS_ACC(x1_B0, 0,0), 33) + 3.28307136047444e+119*pow(OPS_ACC(x1_B0, 0,0), 34) +
      1.29931624724409e+55*pow(OPS_ACC(x1_B0, 0,0), 14) + 2.03277374676903e+35*pow(OPS_ACC(x1_B0, 0,0), 8) +
      1.75352365879372e+64*pow(OPS_ACC(x1_B0, 0,0), 17) + 2.36329800530196e+159*pow(OPS_ACC(x1_B0, 0,0), 46) +
      9.82495140513716e+51*pow(OPS_ACC(x1_B0, 0,0), 13) + 3.21179012013871e-152*pow(OPS_ACC(x1_B0, 0,0), 50) +
      3.24406708850941e+162*pow(OPS_ACC(x1_B0, 0,0), 47) + 2.06395843977666e+68*pow(OPS_ACC(x1_B0, 0,0), 18) +
      2.56410792715746e+136*pow(OPS_ACC(x1_B0, 0,0), 39) + 5.68886701881571e+83*pow(OPS_ACC(x1_B0, 0,0), 23) +
      2.92184978890145e+27*(OPS_ACC(x1_B0, 0,0)*OPS_ACC(x1_B0, 0,0)*OPS_ACC(x1_B0, 0,0)*OPS_ACC(x1_B0, 0,0)*OPS_ACC(x1_B0, 0,0)*OPS_ACC(x1_B0, 0,0)) +
      39540.9735154228*OPS_ACC(x1_B0, 0,0) + 4.61340843173285e+168*pow(OPS_ACC(x1_B0, 0,0), 49) + 1.15119137377047e+91*pow(OPS_ACC(x1_B0, 0,0), 25)
      + 2.37839250560204e+110*pow(OPS_ACC(x1_B0, 0,0), 31) + 6.95370046297886e+93*pow(OPS_ACC(x1_B0, 0,0), 26) +
      2.38984666219479e+42*pow(OPS_ACC(x1_B0, 0,0), 10) + 8.02031157760647e+18*(OPS_ACC(x1_B0, 0,0)*OPS_ACC(x1_B0, 0,0)*OPS_ACC(x1_B0, 0,0)*OPS_ACC(x1_B0, 0,0)) +
      9.11366725602467e+142*pow(OPS_ACC(x1_B0, 0,0), 41) - 5.9189041706891e+61*pow(OPS_ACC(x1_B0, 0,0), 16) -
      2.96239996419098e+132*pow(OPS_ACC(x1_B0, 0,0), 38) - 8.56902326114779e+154*pow(OPS_ACC(x1_B0, 0,0), 45) -
      2.31106495374009e+74*pow(OPS_ACC(x1_B0, 0,0), 20) - 2.61202895553277e+145*pow(OPS_ACC(x1_B0, 0,0), 42) -
      1.90902792812425e+23*(OPS_ACC(x1_B0, 0,0)*OPS_ACC(x1_B0, 0,0)*OPS_ACC(x1_B0, 0,0)*OPS_ACC(x1_B0, 0,0)*OPS_ACC(x1_B0, 0,0)) -
      2.38305687445399e+123*pow(OPS_ACC(x1_B0, 0,0), 35) - 2.53403592909936e+58*pow(OPS_ACC(x1_B0, 0,0), 15) -
      9.19919822419889e+165*pow(OPS_ACC(x1_B0, 0,0), 48) - 201962437995019.0*(OPS_ACC(x1_B0, 0,0)*OPS_ACC(x1_B0, 0,0)*OPS_ACC(x1_B0, 0,0)) -
      3.49222989414674e+106*pow(OPS_ACC(x1_B0, 0,0), 30) - 6.88694545160508e+100*pow(OPS_ACC(x1_B0, 0,0), 28) -
      1.9942490193615e+97*pow(OPS_ACC(x1_B0, 0,0), 27) - 1.19326416753753e+78*pow(OPS_ACC(x1_B0, 0,0), 21) -
      7.07211889201531e+126*pow(OPS_ACC(x1_B0, 0,0), 36) - 9.06476607548832e+38*pow(OPS_ACC(x1_B0, 0,0), 9) -
      1.03014398462665e+104*pow(OPS_ACC(x1_B0, 0,0), 29) - 2.97634744537888e+31*pow(OPS_ACC(x1_B0, 0,0), 7) -
      4.33461534804674e+48*pow(OPS_ACC(x1_B0, 0,0), 12) - 1.56187909102407e+81*pow(OPS_ACC(x1_B0, 0,0), 22) -
      6.91688965498189e+152*pow(OPS_ACC(x1_B0, 0,0), 44) - 2.37001574633349e+45*pow(OPS_ACC(x1_B0, 0,0), 11) -
      3.64474835506301e+149*pow(OPS_ACC(x1_B0, 0,0), 43) - 1.02271130913028e+130*pow(OPS_ACC(x1_B0, 0,0), 37)
)
: (

      86.5834003425591
));

    rhou1 = ((OPS_ACC(x1_B0, 0,0) < 0.000554055405540554) ? (
   0.704253148113786 + 6.12185699413979e+92*pow(OPS_ACC(x1_B0, 0,0), 25) +
      6.40283924795345e+56*pow(OPS_ACC(x1_B0, 0,0), 14) + 8.1976598808294e+156*pow(OPS_ACC(x1_B0, 0,0), 45) +
      3.89980132634298e+20*(OPS_ACC(x1_B0, 0,0)*OPS_ACC(x1_B0, 0,0)*OPS_ACC(x1_B0, 0,0)*OPS_ACC(x1_B0, 0,0)) + 5.22142704491663e+118*pow(OPS_ACC(x1_B0, 0,0), 33) +
      1.22044799356304e+73*pow(OPS_ACC(x1_B0, 0,0), 19) + 5.56571677526156e+85*pow(OPS_ACC(x1_B0, 0,0), 23) +
      1.89201695388508e+138*pow(OPS_ACC(x1_B0, 0,0), 39) + 1.73023969264004e+161*pow(OPS_ACC(x1_B0, 0,0), 46) +
      1.1538062307603e+70*pow(OPS_ACC(x1_B0, 0,0), 18) + 1.96855772779785e+164*pow(OPS_ACC(x1_B0, 0,0), 47) +
      2.42663069391261e+95*pow(OPS_ACC(x1_B0, 0,0), 26) + 1.03824141314418e+37*pow(OPS_ACC(x1_B0, 0,0), 8) +
      4.62172866643428e+133*pow(OPS_ACC(x1_B0, 0,0), 38) + 4.1485248207876e+115*pow(OPS_ACC(x1_B0, 0,0), 32) +
      3.60401801883219e+89*pow(OPS_ACC(x1_B0, 0,0), 24) + 1.27296915481137e+44*pow(OPS_ACC(x1_B0, 0,0), 10) +
      5.51700698536366e+53*pow(OPS_ACC(x1_B0, 0,0), 13) + 4.54218003952598e+141*pow(OPS_ACC(x1_B0, 0,0), 40) +
      4.74394478734374e+144*pow(OPS_ACC(x1_B0, 0,0), 41) + 3.85859093113434e+170*pow(OPS_ACC(x1_B0, 0,0), 49) +
      1.63282627683697e+112*pow(OPS_ACC(x1_B0, 0,0), 31) + 1.50290787007782e+66*pow(OPS_ACC(x1_B0, 0,0), 17) +
      2.20249353495558e-150*pow(OPS_ACC(x1_B0, 0,0), 50) +
      1.45268040376189e+29*(OPS_ACC(x1_B0, 0,0)*OPS_ACC(x1_B0, 0,0)*OPS_ACC(x1_B0, 0,0)*OPS_ACC(x1_B0, 0,0)*OPS_ACC(x1_B0, 0,0)*OPS_ACC(x1_B0, 0,0)) +
      133852667077.071*(OPS_ACC(x1_B0, 0,0)*OPS_ACC(x1_B0, 0,0)) - 4.11171381182013e+147*pow(OPS_ACC(x1_B0, 0,0), 42) -
      1.62109941338031e+76*pow(OPS_ACC(x1_B0, 0,0), 20) - 1.49859148290694e+33*pow(OPS_ACC(x1_B0, 0,0), 7) -
      1.70752817616676e+125*pow(OPS_ACC(x1_B0, 0,0), 35) - 4.71071873015159e+40*pow(OPS_ACC(x1_B0, 0,0), 9) -
      4.00934170731755e+102*pow(OPS_ACC(x1_B0, 0,0), 28) - 1.48337000292806e+60*pow(OPS_ACC(x1_B0, 0,0), 15) -
      3.07901423932589e+63*pow(OPS_ACC(x1_B0, 0,0), 16) - 9.74011798316263e+15*(OPS_ACC(x1_B0, 0,0)*OPS_ACC(x1_B0, 0,0)*OPS_ACC(x1_B0, 0,0)) -
      6.72219435860287e+79*pow(OPS_ACC(x1_B0, 0,0), 21) - 5.30096904022158e+105*pow(OPS_ACC(x1_B0, 0,0), 29) -
      2.17575205789274e+50*pow(OPS_ACC(x1_B0, 0,0), 12) - 4.3101481064531e+128*pow(OPS_ACC(x1_B0, 0,0), 36) -
      1.37211978817903e+99*pow(OPS_ACC(x1_B0, 0,0), 27) - 7.72717709551663e+82*pow(OPS_ACC(x1_B0, 0,0), 22) - 700131.859725696*OPS_ACC(x1_B0, 0,0)
      - 6.95055083757665e+167*pow(OPS_ACC(x1_B0, 0,0), 48) - 1.34829452593554e+47*pow(OPS_ACC(x1_B0, 0,0), 11) -
      2.18130862666441e+107*pow(OPS_ACC(x1_B0, 0,0), 30) - 5.39244861021929e+131*pow(OPS_ACC(x1_B0, 0,0), 37) -
      9.85265173015976e+119*pow(OPS_ACC(x1_B0, 0,0), 34) - 4.20916039017169e+154*pow(OPS_ACC(x1_B0, 0,0), 44) -
      9.38217732873789e+24*(OPS_ACC(x1_B0, 0,0)*OPS_ACC(x1_B0, 0,0)*OPS_ACC(x1_B0, 0,0)*OPS_ACC(x1_B0, 0,0)*OPS_ACC(x1_B0, 0,0)) -
      2.58209677175942e+151*pow(OPS_ACC(x1_B0, 0,0), 43)
)
: (
   4193.65501531314
));

    T = ((OPS_ACC(x1_B0, 0,0) < 0.000554055405540554) ? (
   1494.92335640258 + 2.64872580090291e+120*pow(OPS_ACC(x1_B0, 0,0), 34) +
      5.19956922773838e+146*pow(OPS_ACC(x1_B0, 0,0), 42) + 2.2259392437699e+153*pow(OPS_ACC(x1_B0, 0,0), 44) +
      5.87546352183728e+48*pow(OPS_ACC(x1_B0, 0,0), 12) + 4.29718130228444e+31*pow(OPS_ACC(x1_B0, 0,0), 7) +
      1.52000935963422e+39*pow(OPS_ACC(x1_B0, 0,0), 9) + 6.94238174246588e+58*pow(OPS_ACC(x1_B0, 0,0), 15) + 15532.0145882649*OPS_ACC(x1_B0, 0,0) +
      5.83298115231724e+45*pow(OPS_ACC(x1_B0, 0,0), 11) + 2.285989346544e+127*pow(OPS_ACC(x1_B0, 0,0), 36) +
      1.57626046134794e+104*pow(OPS_ACC(x1_B0, 0,0), 29) + 1.80044511806543e+150*pow(OPS_ACC(x1_B0, 0,0), 43) +
      1.21982104288517e+124*pow(OPS_ACC(x1_B0, 0,0), 35) + 9.99534509402956e+93*pow(OPS_ACC(x1_B0, 0,0), 26) +
      1.10932299620473e+75*pow(OPS_ACC(x1_B0, 0,0), 20) + 1.88141724099714e+101*pow(OPS_ACC(x1_B0, 0,0), 28) +
      9.21049941824155e+97*pow(OPS_ACC(x1_B0, 0,0), 27) + 2.83227019439129e+78*pow(OPS_ACC(x1_B0, 0,0), 21) +
      2.45259482701576e+23*(OPS_ACC(x1_B0, 0,0)*OPS_ACC(x1_B0, 0,0)*OPS_ACC(x1_B0, 0,0)*OPS_ACC(x1_B0, 0,0)*OPS_ACC(x1_B0, 0,0)) +
      1.83283406351692e+130*pow(OPS_ACC(x1_B0, 0,0), 37) + 234260194132087.0*(OPS_ACC(x1_B0, 0,0)*OPS_ACC(x1_B0, 0,0)*OPS_ACC(x1_B0, 0,0)) +
      5.25656731298845e+166*pow(OPS_ACC(x1_B0, 0,0), 48) + 9.62817389019351e+61*pow(OPS_ACC(x1_B0, 0,0), 16) +
      1.81156243602861e+81*pow(OPS_ACC(x1_B0, 0,0), 22) - 1.53162826501083e+55*pow(OPS_ACC(x1_B0, 0,0), 14) -
      2.27562275679452e+107*pow(OPS_ACC(x1_B0, 0,0), 30) - 1.54281027870464e+143*pow(OPS_ACC(x1_B0, 0,0), 41) -
      3.26429224862359e+169*pow(OPS_ACC(x1_B0, 0,0), 49) - 4.73121930355565e+68*pow(OPS_ACC(x1_B0, 0,0), 18) -
      2.09836098361976e+91*pow(OPS_ACC(x1_B0, 0,0), 25) - 2.55162459639318e+140*pow(OPS_ACC(x1_B0, 0,0), 40) -
      9.79791403528433e+18*(OPS_ACC(x1_B0, 0,0)*OPS_ACC(x1_B0, 0,0)*OPS_ACC(x1_B0, 0,0)*OPS_ACC(x1_B0, 0,0)) - 2.62507707543133e+71*pow(OPS_ACC(x1_B0, 0,0), 19) -
      3.00672072875382e+133*pow(OPS_ACC(x1_B0, 0,0), 38) - 1.03426515851009e+163*pow(OPS_ACC(x1_B0, 0,0), 47) -
      14004867423.141*(OPS_ACC(x1_B0, 0,0)*OPS_ACC(x1_B0, 0,0)) - 1.25937284341093e+160*pow(OPS_ACC(x1_B0, 0,0), 46) -
      1.09316163294177e+111*pow(OPS_ACC(x1_B0, 0,0), 31) - 1.45187259298045e-151*pow(OPS_ACC(x1_B0, 0,0), 50) -
      1.7703294676445e+88*pow(OPS_ACC(x1_B0, 0,0), 24) - 2.02190113277919e+156*pow(OPS_ACC(x1_B0, 0,0), 45) -
      1.30404280697706e+65*pow(OPS_ACC(x1_B0, 0,0), 17) - 1.59086631726228e+117*pow(OPS_ACC(x1_B0, 0,0), 33) -
      5.55102639861885e+84*pow(OPS_ACC(x1_B0, 0,0), 23) - 1.40331158468771e+137*pow(OPS_ACC(x1_B0, 0,0), 39) -
      3.96935188053608e+27*(OPS_ACC(x1_B0, 0,0)*OPS_ACC(x1_B0, 0,0)*OPS_ACC(x1_B0, 0,0)*OPS_ACC(x1_B0, 0,0)*OPS_ACC(x1_B0, 0,0)*OPS_ACC(x1_B0, 0,0)) -
      4.48514451422516e+42*pow(OPS_ACC(x1_B0, 0,0), 10) - 2.03098841093001e+114*pow(OPS_ACC(x1_B0, 0,0), 32) -
      3.14207986082458e+35*pow(OPS_ACC(x1_B0, 0,0), 8) - 2.29586028697282e+52*pow(OPS_ACC(x1_B0, 0,0), 13)
)
: (
   288.000000952991
));

   rho = 1202.74707431774/T;

   OPS_ACC(rho_B0, 0,0) = rho;

   OPS_ACC(rhou0_B0, 0,0) = rhou0;

   OPS_ACC(rhou1_B0, 0,0) = rhou1;

   OPS_ACC(rhoE_B0, 0,0) = (0.5*(rhou0*rhou0) + 0.5*(rhou1*rhou1))/rho + invgama*inv2Minf*inv_gamma_m1*T*rho;


    }
  }
}
