//
// auto-generated by ops.py
//

int xdim0_opensbliblock00Kernel028;
int xdim1_opensbliblock00Kernel028;
int xdim2_opensbliblock00Kernel028;
int xdim3_opensbliblock00Kernel028;
int xdim4_opensbliblock00Kernel028;
int xdim5_opensbliblock00Kernel028;
int xdim6_opensbliblock00Kernel028;
int xdim7_opensbliblock00Kernel028;
int xdim8_opensbliblock00Kernel028;
int xdim9_opensbliblock00Kernel028;
int xdim10_opensbliblock00Kernel028;
int xdim11_opensbliblock00Kernel028;
int xdim12_opensbliblock00Kernel028;
int xdim13_opensbliblock00Kernel028;
int xdim14_opensbliblock00Kernel028;
int xdim15_opensbliblock00Kernel028;


//user function



void opensbliblock00Kernel028_c_wrapper(
  double * restrict D00_B0_p,
  double * restrict D01_B0_p,
  double * restrict D10_B0_p,
  double * restrict D11_B0_p,
  double * restrict U0_B0_p,
  double * restrict U1_B0_p,
  double * restrict detJ_B0_p,
  double * restrict p_B0_p,
  double * restrict rhoE_B0_p,
  double * restrict rho_B0_p,
  double * restrict rhou0_B0_p,
  double * restrict rhou1_B0_p,
  double * restrict Residual0_B0_p,
  double * restrict Residual1_B0_p,
  double * restrict Residual2_B0_p,
  double * restrict Residual3_B0_p,
  int * restrict idx,
  int arg_idx0, int arg_idx1,
  int x_size, int y_size) {
  #pragma omp parallel for
  for ( int n_y=0; n_y<y_size; n_y++ ){
    for ( int n_x=0; n_x<x_size; n_x++ ){
      int idx[] = {arg_idx0+n_x, arg_idx1+n_y};
      const ptr_double D00_B0 = { D00_B0_p + n_x*1 + n_y * xdim0_opensbliblock00Kernel028*1, xdim0_opensbliblock00Kernel028};
      const ptr_double D01_B0 = { D01_B0_p + n_x*1 + n_y * xdim1_opensbliblock00Kernel028*1, xdim1_opensbliblock00Kernel028};
      const ptr_double D10_B0 = { D10_B0_p + n_x*1 + n_y * xdim2_opensbliblock00Kernel028*1, xdim2_opensbliblock00Kernel028};
      const ptr_double D11_B0 = { D11_B0_p + n_x*1 + n_y * xdim3_opensbliblock00Kernel028*1, xdim3_opensbliblock00Kernel028};
      const ptr_double U0_B0 = { U0_B0_p + n_x*1 + n_y * xdim4_opensbliblock00Kernel028*1, xdim4_opensbliblock00Kernel028};
      const ptr_double U1_B0 = { U1_B0_p + n_x*1 + n_y * xdim5_opensbliblock00Kernel028*1, xdim5_opensbliblock00Kernel028};
      const ptr_double detJ_B0 = { detJ_B0_p + n_x*1 + n_y * xdim6_opensbliblock00Kernel028*1, xdim6_opensbliblock00Kernel028};
      const ptr_double p_B0 = { p_B0_p + n_x*1 + n_y * xdim7_opensbliblock00Kernel028*1, xdim7_opensbliblock00Kernel028};
      const ptr_double rhoE_B0 = { rhoE_B0_p + n_x*1 + n_y * xdim8_opensbliblock00Kernel028*1, xdim8_opensbliblock00Kernel028};
      const ptr_double rho_B0 = { rho_B0_p + n_x*1 + n_y * xdim9_opensbliblock00Kernel028*1, xdim9_opensbliblock00Kernel028};
      const ptr_double rhou0_B0 = { rhou0_B0_p + n_x*1 + n_y * xdim10_opensbliblock00Kernel028*1, xdim10_opensbliblock00Kernel028};
      const ptr_double rhou1_B0 = { rhou1_B0_p + n_x*1 + n_y * xdim11_opensbliblock00Kernel028*1, xdim11_opensbliblock00Kernel028};
      ptr_double Residual0_B0 = { Residual0_B0_p + n_x*1 + n_y * xdim12_opensbliblock00Kernel028*1, xdim12_opensbliblock00Kernel028};
      ptr_double Residual1_B0 = { Residual1_B0_p + n_x*1 + n_y * xdim13_opensbliblock00Kernel028*1, xdim13_opensbliblock00Kernel028};
      ptr_double Residual2_B0 = { Residual2_B0_p + n_x*1 + n_y * xdim14_opensbliblock00Kernel028*1, xdim14_opensbliblock00Kernel028};
      ptr_double Residual3_B0 = { Residual3_B0_p + n_x*1 + n_y * xdim15_opensbliblock00Kernel028*1, xdim15_opensbliblock00Kernel028};
      
   double d1_D00U0detJprhou0_dx = 0.0;
   double d1_D00U0detJprhou0_dy = 0.0;
   double d1_D01U0detJprhou1_dx = 0.0;
   double d1_D01U0detJprhou1_dy = 0.0;
   double d1_D10U1detJprhou0_dx = 0.0;
   double d1_D10U1detJprhou0_dy = 0.0;
   double d1_D11U1detJprhou1_dx = 0.0;
   double d1_D11U1detJprhou1_dy = 0.0;
   double d1_U0detJprhoE_dx = 0.0;
   double d1_U0detJprhoE_dy = 0.0;
   double d1_U0detJrho_dx = 0.0;
   double d1_U0detJrho_dy = 0.0;
   double d1_U1detJprhoE_dx = 0.0;
   double d1_U1detJprhoE_dy = 0.0;
   double d1_U1detJrho_dx = 0.0;
   double d1_U1detJrho_dy = 0.0;
   if (idx[0] == 0){

       d1_D00U0detJprhou0_dx = (-3*(OPS_ACC(p_B0, 2,0)*OPS_ACC(D00_B0, 2,0) + OPS_ACC(U0_B0, 2,0)*OPS_ACC(rhou0_B0, 2,0))*OPS_ACC(detJ_B0, 2,0) +
            4*(OPS_ACC(p_B0, 1,0)*OPS_ACC(D00_B0, 1,0) + OPS_ACC(U0_B0, 1,0)*OPS_ACC(rhou0_B0, 1,0))*OPS_ACC(detJ_B0, 1,0) - (25.0/12.0)*(OPS_ACC(p_B0, 0,0)*OPS_ACC(D00_B0, 0,0) +
            OPS_ACC(U0_B0, 0,0)*OPS_ACC(rhou0_B0, 0,0))*OPS_ACC(detJ_B0, 0,0) - (1.0/4.0)*(OPS_ACC(p_B0, 4,0)*OPS_ACC(D00_B0, 4,0) +
            OPS_ACC(U0_B0, 4,0)*OPS_ACC(rhou0_B0, 4,0))*OPS_ACC(detJ_B0, 4,0) + ((4.0/3.0))*(OPS_ACC(p_B0, 3,0)*OPS_ACC(D00_B0, 3,0) +
            OPS_ACC(U0_B0, 3,0)*OPS_ACC(rhou0_B0, 3,0))*OPS_ACC(detJ_B0, 3,0))*invDelta0block0;

       d1_D01U0detJprhou1_dx = (-3*(OPS_ACC(p_B0, 2,0)*OPS_ACC(D01_B0, 2,0) + OPS_ACC(U0_B0, 2,0)*OPS_ACC(rhou1_B0, 2,0))*OPS_ACC(detJ_B0, 2,0) +
            4*(OPS_ACC(p_B0, 1,0)*OPS_ACC(D01_B0, 1,0) + OPS_ACC(U0_B0, 1,0)*OPS_ACC(rhou1_B0, 1,0))*OPS_ACC(detJ_B0, 1,0) - (25.0/12.0)*(OPS_ACC(p_B0, 0,0)*OPS_ACC(D01_B0, 0,0) +
            OPS_ACC(U0_B0, 0,0)*OPS_ACC(rhou1_B0, 0,0))*OPS_ACC(detJ_B0, 0,0) - (1.0/4.0)*(OPS_ACC(p_B0, 4,0)*OPS_ACC(D01_B0, 4,0) +
            OPS_ACC(U0_B0, 4,0)*OPS_ACC(rhou1_B0, 4,0))*OPS_ACC(detJ_B0, 4,0) + ((4.0/3.0))*(OPS_ACC(p_B0, 3,0)*OPS_ACC(D01_B0, 3,0) +
            OPS_ACC(U0_B0, 3,0)*OPS_ACC(rhou1_B0, 3,0))*OPS_ACC(detJ_B0, 3,0))*invDelta0block0;

       d1_D10U1detJprhou0_dx = (-3*(OPS_ACC(p_B0, 2,0)*OPS_ACC(D10_B0, 2,0) + OPS_ACC(U1_B0, 2,0)*OPS_ACC(rhou0_B0, 2,0))*OPS_ACC(detJ_B0, 2,0) +
            4*(OPS_ACC(p_B0, 1,0)*OPS_ACC(D10_B0, 1,0) + OPS_ACC(U1_B0, 1,0)*OPS_ACC(rhou0_B0, 1,0))*OPS_ACC(detJ_B0, 1,0) - (25.0/12.0)*(OPS_ACC(p_B0, 0,0)*OPS_ACC(D10_B0, 0,0) +
            OPS_ACC(U1_B0, 0,0)*OPS_ACC(rhou0_B0, 0,0))*OPS_ACC(detJ_B0, 0,0) - (1.0/4.0)*(OPS_ACC(p_B0, 4,0)*OPS_ACC(D10_B0, 4,0) +
            OPS_ACC(U1_B0, 4,0)*OPS_ACC(rhou0_B0, 4,0))*OPS_ACC(detJ_B0, 4,0) + ((4.0/3.0))*(OPS_ACC(p_B0, 3,0)*OPS_ACC(D10_B0, 3,0) +
            OPS_ACC(U1_B0, 3,0)*OPS_ACC(rhou0_B0, 3,0))*OPS_ACC(detJ_B0, 3,0))*invDelta0block0;

       d1_D11U1detJprhou1_dx = (-3*(OPS_ACC(p_B0, 2,0)*OPS_ACC(D11_B0, 2,0) + OPS_ACC(U1_B0, 2,0)*OPS_ACC(rhou1_B0, 2,0))*OPS_ACC(detJ_B0, 2,0) +
            4*(OPS_ACC(p_B0, 1,0)*OPS_ACC(D11_B0, 1,0) + OPS_ACC(U1_B0, 1,0)*OPS_ACC(rhou1_B0, 1,0))*OPS_ACC(detJ_B0, 1,0) - (25.0/12.0)*(OPS_ACC(p_B0, 0,0)*OPS_ACC(D11_B0, 0,0) +
            OPS_ACC(U1_B0, 0,0)*OPS_ACC(rhou1_B0, 0,0))*OPS_ACC(detJ_B0, 0,0) - (1.0/4.0)*(OPS_ACC(p_B0, 4,0)*OPS_ACC(D11_B0, 4,0) +
            OPS_ACC(U1_B0, 4,0)*OPS_ACC(rhou1_B0, 4,0))*OPS_ACC(detJ_B0, 4,0) + ((4.0/3.0))*(OPS_ACC(p_B0, 3,0)*OPS_ACC(D11_B0, 3,0) +
            OPS_ACC(U1_B0, 3,0)*OPS_ACC(rhou1_B0, 3,0))*OPS_ACC(detJ_B0, 3,0))*invDelta0block0;

       d1_U0detJprhoE_dx = (-3*(OPS_ACC(p_B0, 2,0) + OPS_ACC(rhoE_B0, 2,0))*OPS_ACC(U0_B0, 2,0)*OPS_ACC(detJ_B0, 2,0) + 4*(OPS_ACC(p_B0, 1,0) +
            OPS_ACC(rhoE_B0, 1,0))*OPS_ACC(U0_B0, 1,0)*OPS_ACC(detJ_B0, 1,0) - (25.0/12.0)*(OPS_ACC(p_B0, 0,0) + OPS_ACC(rhoE_B0, 0,0))*OPS_ACC(U0_B0, 0,0)*OPS_ACC(detJ_B0, 0,0) -
            (1.0/4.0)*(OPS_ACC(p_B0, 4,0) + OPS_ACC(rhoE_B0, 4,0))*OPS_ACC(U0_B0, 4,0)*OPS_ACC(detJ_B0, 4,0) + ((4.0/3.0))*(OPS_ACC(p_B0, 3,0) +
            OPS_ACC(rhoE_B0, 3,0))*OPS_ACC(U0_B0, 3,0)*OPS_ACC(detJ_B0, 3,0))*invDelta0block0;

       d1_U1detJprhoE_dx = (-3*(OPS_ACC(p_B0, 2,0) + OPS_ACC(rhoE_B0, 2,0))*OPS_ACC(U1_B0, 2,0)*OPS_ACC(detJ_B0, 2,0) + 4*(OPS_ACC(p_B0, 1,0) +
            OPS_ACC(rhoE_B0, 1,0))*OPS_ACC(U1_B0, 1,0)*OPS_ACC(detJ_B0, 1,0) - (25.0/12.0)*(OPS_ACC(p_B0, 0,0) + OPS_ACC(rhoE_B0, 0,0))*OPS_ACC(U1_B0, 0,0)*OPS_ACC(detJ_B0, 0,0) -
            (1.0/4.0)*(OPS_ACC(p_B0, 4,0) + OPS_ACC(rhoE_B0, 4,0))*OPS_ACC(U1_B0, 4,0)*OPS_ACC(detJ_B0, 4,0) + ((4.0/3.0))*(OPS_ACC(p_B0, 3,0) +
            OPS_ACC(rhoE_B0, 3,0))*OPS_ACC(U1_B0, 3,0)*OPS_ACC(detJ_B0, 3,0))*invDelta0block0;

       d1_U0detJrho_dx = (-3*OPS_ACC(U0_B0, 2,0)*OPS_ACC(rho_B0, 2,0)*OPS_ACC(detJ_B0, 2,0) + 4*OPS_ACC(U0_B0, 1,0)*OPS_ACC(rho_B0, 1,0)*OPS_ACC(detJ_B0, 1,0) -
            (25.0/12.0)*OPS_ACC(U0_B0, 0,0)*OPS_ACC(rho_B0, 0,0)*OPS_ACC(detJ_B0, 0,0) - (1.0/4.0)*OPS_ACC(U0_B0, 4,0)*OPS_ACC(rho_B0, 4,0)*OPS_ACC(detJ_B0, 4,0) +
            ((4.0/3.0))*OPS_ACC(U0_B0, 3,0)*OPS_ACC(rho_B0, 3,0)*OPS_ACC(detJ_B0, 3,0))*invDelta0block0;

       d1_U1detJrho_dx = (-3*OPS_ACC(U1_B0, 2,0)*OPS_ACC(rho_B0, 2,0)*OPS_ACC(detJ_B0, 2,0) + 4*OPS_ACC(U1_B0, 1,0)*OPS_ACC(rho_B0, 1,0)*OPS_ACC(detJ_B0, 1,0) -
            (25.0/12.0)*OPS_ACC(U1_B0, 0,0)*OPS_ACC(rho_B0, 0,0)*OPS_ACC(detJ_B0, 0,0) - (1.0/4.0)*OPS_ACC(U1_B0, 4,0)*OPS_ACC(rho_B0, 4,0)*OPS_ACC(detJ_B0, 4,0) +
            ((4.0/3.0))*OPS_ACC(U1_B0, 3,0)*OPS_ACC(rho_B0, 3,0)*OPS_ACC(detJ_B0, 3,0))*invDelta0block0;

   }

   else if (idx[0] == 1){

       d1_D00U0detJprhou0_dx = (-(5.0/6.0)*(OPS_ACC(p_B0, 0,0)*OPS_ACC(D00_B0, 0,0) + OPS_ACC(U0_B0, 0,0)*OPS_ACC(rhou0_B0, 0,0))*OPS_ACC(detJ_B0, 0,0) -
            (1.0/2.0)*(OPS_ACC(p_B0, 2,0)*OPS_ACC(D00_B0, 2,0) + OPS_ACC(U0_B0, 2,0)*OPS_ACC(rhou0_B0, 2,0))*OPS_ACC(detJ_B0, 2,0) -
            (1.0/4.0)*(OPS_ACC(p_B0, -1,0)*OPS_ACC(D00_B0, -1,0) + OPS_ACC(U0_B0, -1,0)*OPS_ACC(rhou0_B0, -1,0))*OPS_ACC(detJ_B0, -1,0) +
            ((1.0/12.0))*(OPS_ACC(p_B0, 3,0)*OPS_ACC(D00_B0, 3,0) + OPS_ACC(U0_B0, 3,0)*OPS_ACC(rhou0_B0, 3,0))*OPS_ACC(detJ_B0, 3,0) +
            ((3.0/2.0))*(OPS_ACC(p_B0, 1,0)*OPS_ACC(D00_B0, 1,0) + OPS_ACC(U0_B0, 1,0)*OPS_ACC(rhou0_B0, 1,0))*OPS_ACC(detJ_B0, 1,0))*invDelta0block0;

       d1_D01U0detJprhou1_dx = (-(5.0/6.0)*(OPS_ACC(p_B0, 0,0)*OPS_ACC(D01_B0, 0,0) + OPS_ACC(U0_B0, 0,0)*OPS_ACC(rhou1_B0, 0,0))*OPS_ACC(detJ_B0, 0,0) -
            (1.0/2.0)*(OPS_ACC(p_B0, 2,0)*OPS_ACC(D01_B0, 2,0) + OPS_ACC(U0_B0, 2,0)*OPS_ACC(rhou1_B0, 2,0))*OPS_ACC(detJ_B0, 2,0) -
            (1.0/4.0)*(OPS_ACC(p_B0, -1,0)*OPS_ACC(D01_B0, -1,0) + OPS_ACC(U0_B0, -1,0)*OPS_ACC(rhou1_B0, -1,0))*OPS_ACC(detJ_B0, -1,0) +
            ((1.0/12.0))*(OPS_ACC(p_B0, 3,0)*OPS_ACC(D01_B0, 3,0) + OPS_ACC(U0_B0, 3,0)*OPS_ACC(rhou1_B0, 3,0))*OPS_ACC(detJ_B0, 3,0) +
            ((3.0/2.0))*(OPS_ACC(p_B0, 1,0)*OPS_ACC(D01_B0, 1,0) + OPS_ACC(U0_B0, 1,0)*OPS_ACC(rhou1_B0, 1,0))*OPS_ACC(detJ_B0, 1,0))*invDelta0block0;

       d1_D10U1detJprhou0_dx = (-(5.0/6.0)*(OPS_ACC(p_B0, 0,0)*OPS_ACC(D10_B0, 0,0) + OPS_ACC(U1_B0, 0,0)*OPS_ACC(rhou0_B0, 0,0))*OPS_ACC(detJ_B0, 0,0) -
            (1.0/2.0)*(OPS_ACC(p_B0, 2,0)*OPS_ACC(D10_B0, 2,0) + OPS_ACC(U1_B0, 2,0)*OPS_ACC(rhou0_B0, 2,0))*OPS_ACC(detJ_B0, 2,0) -
            (1.0/4.0)*(OPS_ACC(p_B0, -1,0)*OPS_ACC(D10_B0, -1,0) + OPS_ACC(U1_B0, -1,0)*OPS_ACC(rhou0_B0, -1,0))*OPS_ACC(detJ_B0, -1,0) +
            ((1.0/12.0))*(OPS_ACC(p_B0, 3,0)*OPS_ACC(D10_B0, 3,0) + OPS_ACC(U1_B0, 3,0)*OPS_ACC(rhou0_B0, 3,0))*OPS_ACC(detJ_B0, 3,0) +
            ((3.0/2.0))*(OPS_ACC(p_B0, 1,0)*OPS_ACC(D10_B0, 1,0) + OPS_ACC(U1_B0, 1,0)*OPS_ACC(rhou0_B0, 1,0))*OPS_ACC(detJ_B0, 1,0))*invDelta0block0;

       d1_D11U1detJprhou1_dx = (-(5.0/6.0)*(OPS_ACC(p_B0, 0,0)*OPS_ACC(D11_B0, 0,0) + OPS_ACC(U1_B0, 0,0)*OPS_ACC(rhou1_B0, 0,0))*OPS_ACC(detJ_B0, 0,0) -
            (1.0/2.0)*(OPS_ACC(p_B0, 2,0)*OPS_ACC(D11_B0, 2,0) + OPS_ACC(U1_B0, 2,0)*OPS_ACC(rhou1_B0, 2,0))*OPS_ACC(detJ_B0, 2,0) -
            (1.0/4.0)*(OPS_ACC(p_B0, -1,0)*OPS_ACC(D11_B0, -1,0) + OPS_ACC(U1_B0, -1,0)*OPS_ACC(rhou1_B0, -1,0))*OPS_ACC(detJ_B0, -1,0) +
            ((1.0/12.0))*(OPS_ACC(p_B0, 3,0)*OPS_ACC(D11_B0, 3,0) + OPS_ACC(U1_B0, 3,0)*OPS_ACC(rhou1_B0, 3,0))*OPS_ACC(detJ_B0, 3,0) +
            ((3.0/2.0))*(OPS_ACC(p_B0, 1,0)*OPS_ACC(D11_B0, 1,0) + OPS_ACC(U1_B0, 1,0)*OPS_ACC(rhou1_B0, 1,0))*OPS_ACC(detJ_B0, 1,0))*invDelta0block0;

       d1_U0detJprhoE_dx = (-(5.0/6.0)*(OPS_ACC(p_B0, 0,0) + OPS_ACC(rhoE_B0, 0,0))*OPS_ACC(U0_B0, 0,0)*OPS_ACC(detJ_B0, 0,0) - (1.0/2.0)*(OPS_ACC(p_B0, 2,0) +
            OPS_ACC(rhoE_B0, 2,0))*OPS_ACC(U0_B0, 2,0)*OPS_ACC(detJ_B0, 2,0) - (1.0/4.0)*(OPS_ACC(p_B0, -1,0) + OPS_ACC(rhoE_B0, -1,0))*OPS_ACC(U0_B0, -1,0)*OPS_ACC(detJ_B0, -1,0) +
            ((1.0/12.0))*(OPS_ACC(p_B0, 3,0) + OPS_ACC(rhoE_B0, 3,0))*OPS_ACC(U0_B0, 3,0)*OPS_ACC(detJ_B0, 3,0) + ((3.0/2.0))*(OPS_ACC(p_B0, 1,0) +
            OPS_ACC(rhoE_B0, 1,0))*OPS_ACC(U0_B0, 1,0)*OPS_ACC(detJ_B0, 1,0))*invDelta0block0;

       d1_U1detJprhoE_dx = (-(5.0/6.0)*(OPS_ACC(p_B0, 0,0) + OPS_ACC(rhoE_B0, 0,0))*OPS_ACC(U1_B0, 0,0)*OPS_ACC(detJ_B0, 0,0) - (1.0/2.0)*(OPS_ACC(p_B0, 2,0) +
            OPS_ACC(rhoE_B0, 2,0))*OPS_ACC(U1_B0, 2,0)*OPS_ACC(detJ_B0, 2,0) - (1.0/4.0)*(OPS_ACC(p_B0, -1,0) + OPS_ACC(rhoE_B0, -1,0))*OPS_ACC(U1_B0, -1,0)*OPS_ACC(detJ_B0, -1,0) +
            ((1.0/12.0))*(OPS_ACC(p_B0, 3,0) + OPS_ACC(rhoE_B0, 3,0))*OPS_ACC(U1_B0, 3,0)*OPS_ACC(detJ_B0, 3,0) + ((3.0/2.0))*(OPS_ACC(p_B0, 1,0) +
            OPS_ACC(rhoE_B0, 1,0))*OPS_ACC(U1_B0, 1,0)*OPS_ACC(detJ_B0, 1,0))*invDelta0block0;

       d1_U0detJrho_dx = (-(5.0/6.0)*OPS_ACC(U0_B0, 0,0)*OPS_ACC(rho_B0, 0,0)*OPS_ACC(detJ_B0, 0,0) - (1.0/2.0)*OPS_ACC(U0_B0, 2,0)*OPS_ACC(rho_B0, 2,0)*OPS_ACC(detJ_B0, 2,0)
            - (1.0/4.0)*OPS_ACC(U0_B0, -1,0)*OPS_ACC(rho_B0, -1,0)*OPS_ACC(detJ_B0, -1,0) + ((1.0/12.0))*OPS_ACC(U0_B0, 3,0)*OPS_ACC(rho_B0, 3,0)*OPS_ACC(detJ_B0, 3,0) +
            ((3.0/2.0))*OPS_ACC(U0_B0, 1,0)*OPS_ACC(rho_B0, 1,0)*OPS_ACC(detJ_B0, 1,0))*invDelta0block0;

       d1_U1detJrho_dx = (-(5.0/6.0)*OPS_ACC(U1_B0, 0,0)*OPS_ACC(rho_B0, 0,0)*OPS_ACC(detJ_B0, 0,0) - (1.0/2.0)*OPS_ACC(U1_B0, 2,0)*OPS_ACC(rho_B0, 2,0)*OPS_ACC(detJ_B0, 2,0)
            - (1.0/4.0)*OPS_ACC(U1_B0, -1,0)*OPS_ACC(rho_B0, -1,0)*OPS_ACC(detJ_B0, -1,0) + ((1.0/12.0))*OPS_ACC(U1_B0, 3,0)*OPS_ACC(rho_B0, 3,0)*OPS_ACC(detJ_B0, 3,0) +
            ((3.0/2.0))*OPS_ACC(U1_B0, 1,0)*OPS_ACC(rho_B0, 1,0)*OPS_ACC(detJ_B0, 1,0))*invDelta0block0;

   }

   else if (idx[0] == -1 + block0np0){

       d1_D00U0detJprhou0_dx = (-4*(OPS_ACC(p_B0, -1,0)*OPS_ACC(D00_B0, -1,0) + OPS_ACC(U0_B0, -1,0)*OPS_ACC(rhou0_B0, -1,0))*OPS_ACC(detJ_B0, -1,0) +
            3*(OPS_ACC(p_B0, -2,0)*OPS_ACC(D00_B0, -2,0) + OPS_ACC(U0_B0, -2,0)*OPS_ACC(rhou0_B0, -2,0))*OPS_ACC(detJ_B0, -2,0) - (4.0/3.0)*(OPS_ACC(p_B0, -3,0)*OPS_ACC(D00_B0, -3,0)
            + OPS_ACC(U0_B0, -3,0)*OPS_ACC(rhou0_B0, -3,0))*OPS_ACC(detJ_B0, -3,0) + ((1.0/4.0))*(OPS_ACC(p_B0, -4,0)*OPS_ACC(D00_B0, -4,0) +
            OPS_ACC(U0_B0, -4,0)*OPS_ACC(rhou0_B0, -4,0))*OPS_ACC(detJ_B0, -4,0) + ((25.0/12.0))*(OPS_ACC(p_B0, 0,0)*OPS_ACC(D00_B0, 0,0) +
            OPS_ACC(U0_B0, 0,0)*OPS_ACC(rhou0_B0, 0,0))*OPS_ACC(detJ_B0, 0,0))*invDelta0block0;

       d1_D01U0detJprhou1_dx = (-4*(OPS_ACC(p_B0, -1,0)*OPS_ACC(D01_B0, -1,0) + OPS_ACC(U0_B0, -1,0)*OPS_ACC(rhou1_B0, -1,0))*OPS_ACC(detJ_B0, -1,0) +
            3*(OPS_ACC(p_B0, -2,0)*OPS_ACC(D01_B0, -2,0) + OPS_ACC(U0_B0, -2,0)*OPS_ACC(rhou1_B0, -2,0))*OPS_ACC(detJ_B0, -2,0) - (4.0/3.0)*(OPS_ACC(p_B0, -3,0)*OPS_ACC(D01_B0, -3,0)
            + OPS_ACC(U0_B0, -3,0)*OPS_ACC(rhou1_B0, -3,0))*OPS_ACC(detJ_B0, -3,0) + ((1.0/4.0))*(OPS_ACC(p_B0, -4,0)*OPS_ACC(D01_B0, -4,0) +
            OPS_ACC(U0_B0, -4,0)*OPS_ACC(rhou1_B0, -4,0))*OPS_ACC(detJ_B0, -4,0) + ((25.0/12.0))*(OPS_ACC(p_B0, 0,0)*OPS_ACC(D01_B0, 0,0) +
            OPS_ACC(U0_B0, 0,0)*OPS_ACC(rhou1_B0, 0,0))*OPS_ACC(detJ_B0, 0,0))*invDelta0block0;

       d1_D10U1detJprhou0_dx = (-4*(OPS_ACC(p_B0, -1,0)*OPS_ACC(D10_B0, -1,0) + OPS_ACC(U1_B0, -1,0)*OPS_ACC(rhou0_B0, -1,0))*OPS_ACC(detJ_B0, -1,0) +
            3*(OPS_ACC(p_B0, -2,0)*OPS_ACC(D10_B0, -2,0) + OPS_ACC(U1_B0, -2,0)*OPS_ACC(rhou0_B0, -2,0))*OPS_ACC(detJ_B0, -2,0) - (4.0/3.0)*(OPS_ACC(p_B0, -3,0)*OPS_ACC(D10_B0, -3,0)
            + OPS_ACC(U1_B0, -3,0)*OPS_ACC(rhou0_B0, -3,0))*OPS_ACC(detJ_B0, -3,0) + ((1.0/4.0))*(OPS_ACC(p_B0, -4,0)*OPS_ACC(D10_B0, -4,0) +
            OPS_ACC(U1_B0, -4,0)*OPS_ACC(rhou0_B0, -4,0))*OPS_ACC(detJ_B0, -4,0) + ((25.0/12.0))*(OPS_ACC(p_B0, 0,0)*OPS_ACC(D10_B0, 0,0) +
            OPS_ACC(U1_B0, 0,0)*OPS_ACC(rhou0_B0, 0,0))*OPS_ACC(detJ_B0, 0,0))*invDelta0block0;

       d1_D11U1detJprhou1_dx = (-4*(OPS_ACC(p_B0, -1,0)*OPS_ACC(D11_B0, -1,0) + OPS_ACC(U1_B0, -1,0)*OPS_ACC(rhou1_B0, -1,0))*OPS_ACC(detJ_B0, -1,0) +
            3*(OPS_ACC(p_B0, -2,0)*OPS_ACC(D11_B0, -2,0) + OPS_ACC(U1_B0, -2,0)*OPS_ACC(rhou1_B0, -2,0))*OPS_ACC(detJ_B0, -2,0) - (4.0/3.0)*(OPS_ACC(p_B0, -3,0)*OPS_ACC(D11_B0, -3,0)
            + OPS_ACC(U1_B0, -3,0)*OPS_ACC(rhou1_B0, -3,0))*OPS_ACC(detJ_B0, -3,0) + ((1.0/4.0))*(OPS_ACC(p_B0, -4,0)*OPS_ACC(D11_B0, -4,0) +
            OPS_ACC(U1_B0, -4,0)*OPS_ACC(rhou1_B0, -4,0))*OPS_ACC(detJ_B0, -4,0) + ((25.0/12.0))*(OPS_ACC(p_B0, 0,0)*OPS_ACC(D11_B0, 0,0) +
            OPS_ACC(U1_B0, 0,0)*OPS_ACC(rhou1_B0, 0,0))*OPS_ACC(detJ_B0, 0,0))*invDelta0block0;

       d1_U0detJprhoE_dx = (-4*(OPS_ACC(p_B0, -1,0) + OPS_ACC(rhoE_B0, -1,0))*OPS_ACC(U0_B0, -1,0)*OPS_ACC(detJ_B0, -1,0) + 3*(OPS_ACC(p_B0, -2,0) +
            OPS_ACC(rhoE_B0, -2,0))*OPS_ACC(U0_B0, -2,0)*OPS_ACC(detJ_B0, -2,0) - (4.0/3.0)*(OPS_ACC(p_B0, -3,0) + OPS_ACC(rhoE_B0, -3,0))*OPS_ACC(U0_B0, -3,0)*OPS_ACC(detJ_B0, -3,0)
            + ((1.0/4.0))*(OPS_ACC(p_B0, -4,0) + OPS_ACC(rhoE_B0, -4,0))*OPS_ACC(U0_B0, -4,0)*OPS_ACC(detJ_B0, -4,0) + ((25.0/12.0))*(OPS_ACC(p_B0, 0,0) +
            OPS_ACC(rhoE_B0, 0,0))*OPS_ACC(U0_B0, 0,0)*OPS_ACC(detJ_B0, 0,0))*invDelta0block0;

       d1_U1detJprhoE_dx = (-4*(OPS_ACC(p_B0, -1,0) + OPS_ACC(rhoE_B0, -1,0))*OPS_ACC(U1_B0, -1,0)*OPS_ACC(detJ_B0, -1,0) + 3*(OPS_ACC(p_B0, -2,0) +
            OPS_ACC(rhoE_B0, -2,0))*OPS_ACC(U1_B0, -2,0)*OPS_ACC(detJ_B0, -2,0) - (4.0/3.0)*(OPS_ACC(p_B0, -3,0) + OPS_ACC(rhoE_B0, -3,0))*OPS_ACC(U1_B0, -3,0)*OPS_ACC(detJ_B0, -3,0)
            + ((1.0/4.0))*(OPS_ACC(p_B0, -4,0) + OPS_ACC(rhoE_B0, -4,0))*OPS_ACC(U1_B0, -4,0)*OPS_ACC(detJ_B0, -4,0) + ((25.0/12.0))*(OPS_ACC(p_B0, 0,0) +
            OPS_ACC(rhoE_B0, 0,0))*OPS_ACC(U1_B0, 0,0)*OPS_ACC(detJ_B0, 0,0))*invDelta0block0;

       d1_U0detJrho_dx = (-4*OPS_ACC(U0_B0, -1,0)*OPS_ACC(rho_B0, -1,0)*OPS_ACC(detJ_B0, -1,0) + 3*OPS_ACC(U0_B0, -2,0)*OPS_ACC(rho_B0, -2,0)*OPS_ACC(detJ_B0, -2,0) -
            (4.0/3.0)*OPS_ACC(U0_B0, -3,0)*OPS_ACC(rho_B0, -3,0)*OPS_ACC(detJ_B0, -3,0) + ((1.0/4.0))*OPS_ACC(U0_B0, -4,0)*OPS_ACC(rho_B0, -4,0)*OPS_ACC(detJ_B0, -4,0) +
            ((25.0/12.0))*OPS_ACC(U0_B0, 0,0)*OPS_ACC(rho_B0, 0,0)*OPS_ACC(detJ_B0, 0,0))*invDelta0block0;

       d1_U1detJrho_dx = (-4*OPS_ACC(U1_B0, -1,0)*OPS_ACC(rho_B0, -1,0)*OPS_ACC(detJ_B0, -1,0) + 3*OPS_ACC(U1_B0, -2,0)*OPS_ACC(rho_B0, -2,0)*OPS_ACC(detJ_B0, -2,0) -
            (4.0/3.0)*OPS_ACC(U1_B0, -3,0)*OPS_ACC(rho_B0, -3,0)*OPS_ACC(detJ_B0, -3,0) + ((1.0/4.0))*OPS_ACC(U1_B0, -4,0)*OPS_ACC(rho_B0, -4,0)*OPS_ACC(detJ_B0, -4,0) +
            ((25.0/12.0))*OPS_ACC(U1_B0, 0,0)*OPS_ACC(rho_B0, 0,0)*OPS_ACC(detJ_B0, 0,0))*invDelta0block0;

   }

   else if (idx[0] == -2 + block0np0){

       d1_D00U0detJprhou0_dx = (((1.0/2.0))*(OPS_ACC(p_B0, -2,0)*OPS_ACC(D00_B0, -2,0) + OPS_ACC(U0_B0, -2,0)*OPS_ACC(rhou0_B0, -2,0))*OPS_ACC(detJ_B0, -2,0) -
            (3.0/2.0)*(OPS_ACC(p_B0, -1,0)*OPS_ACC(D00_B0, -1,0) + OPS_ACC(U0_B0, -1,0)*OPS_ACC(rhou0_B0, -1,0))*OPS_ACC(detJ_B0, -1,0) -
            (1.0/12.0)*(OPS_ACC(p_B0, -3,0)*OPS_ACC(D00_B0, -3,0) + OPS_ACC(U0_B0, -3,0)*OPS_ACC(rhou0_B0, -3,0))*OPS_ACC(detJ_B0, -3,0) +
            ((1.0/4.0))*(OPS_ACC(p_B0, 1,0)*OPS_ACC(D00_B0, 1,0) + OPS_ACC(U0_B0, 1,0)*OPS_ACC(rhou0_B0, 1,0))*OPS_ACC(detJ_B0, 1,0) +
            ((5.0/6.0))*(OPS_ACC(p_B0, 0,0)*OPS_ACC(D00_B0, 0,0) + OPS_ACC(U0_B0, 0,0)*OPS_ACC(rhou0_B0, 0,0))*OPS_ACC(detJ_B0, 0,0))*invDelta0block0;

       d1_D01U0detJprhou1_dx = (((1.0/2.0))*(OPS_ACC(p_B0, -2,0)*OPS_ACC(D01_B0, -2,0) + OPS_ACC(U0_B0, -2,0)*OPS_ACC(rhou1_B0, -2,0))*OPS_ACC(detJ_B0, -2,0) -
            (3.0/2.0)*(OPS_ACC(p_B0, -1,0)*OPS_ACC(D01_B0, -1,0) + OPS_ACC(U0_B0, -1,0)*OPS_ACC(rhou1_B0, -1,0))*OPS_ACC(detJ_B0, -1,0) -
            (1.0/12.0)*(OPS_ACC(p_B0, -3,0)*OPS_ACC(D01_B0, -3,0) + OPS_ACC(U0_B0, -3,0)*OPS_ACC(rhou1_B0, -3,0))*OPS_ACC(detJ_B0, -3,0) +
            ((1.0/4.0))*(OPS_ACC(p_B0, 1,0)*OPS_ACC(D01_B0, 1,0) + OPS_ACC(U0_B0, 1,0)*OPS_ACC(rhou1_B0, 1,0))*OPS_ACC(detJ_B0, 1,0) +
            ((5.0/6.0))*(OPS_ACC(p_B0, 0,0)*OPS_ACC(D01_B0, 0,0) + OPS_ACC(U0_B0, 0,0)*OPS_ACC(rhou1_B0, 0,0))*OPS_ACC(detJ_B0, 0,0))*invDelta0block0;

       d1_D10U1detJprhou0_dx = (((1.0/2.0))*(OPS_ACC(p_B0, -2,0)*OPS_ACC(D10_B0, -2,0) + OPS_ACC(U1_B0, -2,0)*OPS_ACC(rhou0_B0, -2,0))*OPS_ACC(detJ_B0, -2,0) -
            (3.0/2.0)*(OPS_ACC(p_B0, -1,0)*OPS_ACC(D10_B0, -1,0) + OPS_ACC(U1_B0, -1,0)*OPS_ACC(rhou0_B0, -1,0))*OPS_ACC(detJ_B0, -1,0) -
            (1.0/12.0)*(OPS_ACC(p_B0, -3,0)*OPS_ACC(D10_B0, -3,0) + OPS_ACC(U1_B0, -3,0)*OPS_ACC(rhou0_B0, -3,0))*OPS_ACC(detJ_B0, -3,0) +
            ((1.0/4.0))*(OPS_ACC(p_B0, 1,0)*OPS_ACC(D10_B0, 1,0) + OPS_ACC(U1_B0, 1,0)*OPS_ACC(rhou0_B0, 1,0))*OPS_ACC(detJ_B0, 1,0) +
            ((5.0/6.0))*(OPS_ACC(p_B0, 0,0)*OPS_ACC(D10_B0, 0,0) + OPS_ACC(U1_B0, 0,0)*OPS_ACC(rhou0_B0, 0,0))*OPS_ACC(detJ_B0, 0,0))*invDelta0block0;

       d1_D11U1detJprhou1_dx = (((1.0/2.0))*(OPS_ACC(p_B0, -2,0)*OPS_ACC(D11_B0, -2,0) + OPS_ACC(U1_B0, -2,0)*OPS_ACC(rhou1_B0, -2,0))*OPS_ACC(detJ_B0, -2,0) -
            (3.0/2.0)*(OPS_ACC(p_B0, -1,0)*OPS_ACC(D11_B0, -1,0) + OPS_ACC(U1_B0, -1,0)*OPS_ACC(rhou1_B0, -1,0))*OPS_ACC(detJ_B0, -1,0) -
            (1.0/12.0)*(OPS_ACC(p_B0, -3,0)*OPS_ACC(D11_B0, -3,0) + OPS_ACC(U1_B0, -3,0)*OPS_ACC(rhou1_B0, -3,0))*OPS_ACC(detJ_B0, -3,0) +
            ((1.0/4.0))*(OPS_ACC(p_B0, 1,0)*OPS_ACC(D11_B0, 1,0) + OPS_ACC(U1_B0, 1,0)*OPS_ACC(rhou1_B0, 1,0))*OPS_ACC(detJ_B0, 1,0) +
            ((5.0/6.0))*(OPS_ACC(p_B0, 0,0)*OPS_ACC(D11_B0, 0,0) + OPS_ACC(U1_B0, 0,0)*OPS_ACC(rhou1_B0, 0,0))*OPS_ACC(detJ_B0, 0,0))*invDelta0block0;

       d1_U0detJprhoE_dx = (((1.0/2.0))*(OPS_ACC(p_B0, -2,0) + OPS_ACC(rhoE_B0, -2,0))*OPS_ACC(U0_B0, -2,0)*OPS_ACC(detJ_B0, -2,0) - (3.0/2.0)*(OPS_ACC(p_B0, -1,0) +
            OPS_ACC(rhoE_B0, -1,0))*OPS_ACC(U0_B0, -1,0)*OPS_ACC(detJ_B0, -1,0) - (1.0/12.0)*(OPS_ACC(p_B0, -3,0) + OPS_ACC(rhoE_B0, -3,0))*OPS_ACC(U0_B0, -3,0)*OPS_ACC(detJ_B0, -3,0)
            + ((1.0/4.0))*(OPS_ACC(p_B0, 1,0) + OPS_ACC(rhoE_B0, 1,0))*OPS_ACC(U0_B0, 1,0)*OPS_ACC(detJ_B0, 1,0) + ((5.0/6.0))*(OPS_ACC(p_B0, 0,0) +
            OPS_ACC(rhoE_B0, 0,0))*OPS_ACC(U0_B0, 0,0)*OPS_ACC(detJ_B0, 0,0))*invDelta0block0;

       d1_U1detJprhoE_dx = (((1.0/2.0))*(OPS_ACC(p_B0, -2,0) + OPS_ACC(rhoE_B0, -2,0))*OPS_ACC(U1_B0, -2,0)*OPS_ACC(detJ_B0, -2,0) - (3.0/2.0)*(OPS_ACC(p_B0, -1,0) +
            OPS_ACC(rhoE_B0, -1,0))*OPS_ACC(U1_B0, -1,0)*OPS_ACC(detJ_B0, -1,0) - (1.0/12.0)*(OPS_ACC(p_B0, -3,0) + OPS_ACC(rhoE_B0, -3,0))*OPS_ACC(U1_B0, -3,0)*OPS_ACC(detJ_B0, -3,0)
            + ((1.0/4.0))*(OPS_ACC(p_B0, 1,0) + OPS_ACC(rhoE_B0, 1,0))*OPS_ACC(U1_B0, 1,0)*OPS_ACC(detJ_B0, 1,0) + ((5.0/6.0))*(OPS_ACC(p_B0, 0,0) +
            OPS_ACC(rhoE_B0, 0,0))*OPS_ACC(U1_B0, 0,0)*OPS_ACC(detJ_B0, 0,0))*invDelta0block0;

       d1_U0detJrho_dx = (((1.0/2.0))*OPS_ACC(U0_B0, -2,0)*OPS_ACC(rho_B0, -2,0)*OPS_ACC(detJ_B0, -2,0) -
            (3.0/2.0)*OPS_ACC(U0_B0, -1,0)*OPS_ACC(rho_B0, -1,0)*OPS_ACC(detJ_B0, -1,0) - (1.0/12.0)*OPS_ACC(U0_B0, -3,0)*OPS_ACC(rho_B0, -3,0)*OPS_ACC(detJ_B0, -3,0) +
            ((1.0/4.0))*OPS_ACC(U0_B0, 1,0)*OPS_ACC(rho_B0, 1,0)*OPS_ACC(detJ_B0, 1,0) +
            ((5.0/6.0))*OPS_ACC(U0_B0, 0,0)*OPS_ACC(rho_B0, 0,0)*OPS_ACC(detJ_B0, 0,0))*invDelta0block0;

       d1_U1detJrho_dx = (((1.0/2.0))*OPS_ACC(U1_B0, -2,0)*OPS_ACC(rho_B0, -2,0)*OPS_ACC(detJ_B0, -2,0) -
            (3.0/2.0)*OPS_ACC(U1_B0, -1,0)*OPS_ACC(rho_B0, -1,0)*OPS_ACC(detJ_B0, -1,0) - (1.0/12.0)*OPS_ACC(U1_B0, -3,0)*OPS_ACC(rho_B0, -3,0)*OPS_ACC(detJ_B0, -3,0) +
            ((1.0/4.0))*OPS_ACC(U1_B0, 1,0)*OPS_ACC(rho_B0, 1,0)*OPS_ACC(detJ_B0, 1,0) +
            ((5.0/6.0))*OPS_ACC(U1_B0, 0,0)*OPS_ACC(rho_B0, 0,0)*OPS_ACC(detJ_B0, 0,0))*invDelta0block0;

   }

   else{

       d1_D00U0detJprhou0_dx = (-(2.0/3.0)*(OPS_ACC(p_B0, -1,0)*OPS_ACC(D00_B0, -1,0) + OPS_ACC(U0_B0, -1,0)*OPS_ACC(rhou0_B0, -1,0))*OPS_ACC(detJ_B0, -1,0) -
            (1.0/12.0)*(OPS_ACC(p_B0, 2,0)*OPS_ACC(D00_B0, 2,0) + OPS_ACC(U0_B0, 2,0)*OPS_ACC(rhou0_B0, 2,0))*OPS_ACC(detJ_B0, 2,0) +
            ((1.0/12.0))*(OPS_ACC(p_B0, -2,0)*OPS_ACC(D00_B0, -2,0) + OPS_ACC(U0_B0, -2,0)*OPS_ACC(rhou0_B0, -2,0))*OPS_ACC(detJ_B0, -2,0) +
            ((2.0/3.0))*(OPS_ACC(p_B0, 1,0)*OPS_ACC(D00_B0, 1,0) + OPS_ACC(U0_B0, 1,0)*OPS_ACC(rhou0_B0, 1,0))*OPS_ACC(detJ_B0, 1,0))*invDelta0block0;

       d1_D01U0detJprhou1_dx = (-(2.0/3.0)*(OPS_ACC(p_B0, -1,0)*OPS_ACC(D01_B0, -1,0) + OPS_ACC(U0_B0, -1,0)*OPS_ACC(rhou1_B0, -1,0))*OPS_ACC(detJ_B0, -1,0) -
            (1.0/12.0)*(OPS_ACC(p_B0, 2,0)*OPS_ACC(D01_B0, 2,0) + OPS_ACC(U0_B0, 2,0)*OPS_ACC(rhou1_B0, 2,0))*OPS_ACC(detJ_B0, 2,0) +
            ((1.0/12.0))*(OPS_ACC(p_B0, -2,0)*OPS_ACC(D01_B0, -2,0) + OPS_ACC(U0_B0, -2,0)*OPS_ACC(rhou1_B0, -2,0))*OPS_ACC(detJ_B0, -2,0) +
            ((2.0/3.0))*(OPS_ACC(p_B0, 1,0)*OPS_ACC(D01_B0, 1,0) + OPS_ACC(U0_B0, 1,0)*OPS_ACC(rhou1_B0, 1,0))*OPS_ACC(detJ_B0, 1,0))*invDelta0block0;

       d1_D10U1detJprhou0_dx = (-(2.0/3.0)*(OPS_ACC(p_B0, -1,0)*OPS_ACC(D10_B0, -1,0) + OPS_ACC(U1_B0, -1,0)*OPS_ACC(rhou0_B0, -1,0))*OPS_ACC(detJ_B0, -1,0) -
            (1.0/12.0)*(OPS_ACC(p_B0, 2,0)*OPS_ACC(D10_B0, 2,0) + OPS_ACC(U1_B0, 2,0)*OPS_ACC(rhou0_B0, 2,0))*OPS_ACC(detJ_B0, 2,0) +
            ((1.0/12.0))*(OPS_ACC(p_B0, -2,0)*OPS_ACC(D10_B0, -2,0) + OPS_ACC(U1_B0, -2,0)*OPS_ACC(rhou0_B0, -2,0))*OPS_ACC(detJ_B0, -2,0) +
            ((2.0/3.0))*(OPS_ACC(p_B0, 1,0)*OPS_ACC(D10_B0, 1,0) + OPS_ACC(U1_B0, 1,0)*OPS_ACC(rhou0_B0, 1,0))*OPS_ACC(detJ_B0, 1,0))*invDelta0block0;

       d1_D11U1detJprhou1_dx = (-(2.0/3.0)*(OPS_ACC(p_B0, -1,0)*OPS_ACC(D11_B0, -1,0) + OPS_ACC(U1_B0, -1,0)*OPS_ACC(rhou1_B0, -1,0))*OPS_ACC(detJ_B0, -1,0) -
            (1.0/12.0)*(OPS_ACC(p_B0, 2,0)*OPS_ACC(D11_B0, 2,0) + OPS_ACC(U1_B0, 2,0)*OPS_ACC(rhou1_B0, 2,0))*OPS_ACC(detJ_B0, 2,0) +
            ((1.0/12.0))*(OPS_ACC(p_B0, -2,0)*OPS_ACC(D11_B0, -2,0) + OPS_ACC(U1_B0, -2,0)*OPS_ACC(rhou1_B0, -2,0))*OPS_ACC(detJ_B0, -2,0) +
            ((2.0/3.0))*(OPS_ACC(p_B0, 1,0)*OPS_ACC(D11_B0, 1,0) + OPS_ACC(U1_B0, 1,0)*OPS_ACC(rhou1_B0, 1,0))*OPS_ACC(detJ_B0, 1,0))*invDelta0block0;

       d1_U0detJprhoE_dx = (-(2.0/3.0)*(OPS_ACC(p_B0, -1,0) + OPS_ACC(rhoE_B0, -1,0))*OPS_ACC(U0_B0, -1,0)*OPS_ACC(detJ_B0, -1,0) - (1.0/12.0)*(OPS_ACC(p_B0, 2,0) +
            OPS_ACC(rhoE_B0, 2,0))*OPS_ACC(U0_B0, 2,0)*OPS_ACC(detJ_B0, 2,0) + ((1.0/12.0))*(OPS_ACC(p_B0, -2,0) + OPS_ACC(rhoE_B0, -2,0))*OPS_ACC(U0_B0, -2,0)*OPS_ACC(detJ_B0, -2,0)
            + ((2.0/3.0))*(OPS_ACC(p_B0, 1,0) + OPS_ACC(rhoE_B0, 1,0))*OPS_ACC(U0_B0, 1,0)*OPS_ACC(detJ_B0, 1,0))*invDelta0block0;

       d1_U1detJprhoE_dx = (-(2.0/3.0)*(OPS_ACC(p_B0, -1,0) + OPS_ACC(rhoE_B0, -1,0))*OPS_ACC(U1_B0, -1,0)*OPS_ACC(detJ_B0, -1,0) - (1.0/12.0)*(OPS_ACC(p_B0, 2,0) +
            OPS_ACC(rhoE_B0, 2,0))*OPS_ACC(U1_B0, 2,0)*OPS_ACC(detJ_B0, 2,0) + ((1.0/12.0))*(OPS_ACC(p_B0, -2,0) + OPS_ACC(rhoE_B0, -2,0))*OPS_ACC(U1_B0, -2,0)*OPS_ACC(detJ_B0, -2,0)
            + ((2.0/3.0))*(OPS_ACC(p_B0, 1,0) + OPS_ACC(rhoE_B0, 1,0))*OPS_ACC(U1_B0, 1,0)*OPS_ACC(detJ_B0, 1,0))*invDelta0block0;

       d1_U0detJrho_dx = (-(2.0/3.0)*OPS_ACC(U0_B0, -1,0)*OPS_ACC(rho_B0, -1,0)*OPS_ACC(detJ_B0, -1,0) -
            (1.0/12.0)*OPS_ACC(U0_B0, 2,0)*OPS_ACC(rho_B0, 2,0)*OPS_ACC(detJ_B0, 2,0) + ((1.0/12.0))*OPS_ACC(U0_B0, -2,0)*OPS_ACC(rho_B0, -2,0)*OPS_ACC(detJ_B0, -2,0) +
            ((2.0/3.0))*OPS_ACC(U0_B0, 1,0)*OPS_ACC(rho_B0, 1,0)*OPS_ACC(detJ_B0, 1,0))*invDelta0block0;

       d1_U1detJrho_dx = (-(2.0/3.0)*OPS_ACC(U1_B0, -1,0)*OPS_ACC(rho_B0, -1,0)*OPS_ACC(detJ_B0, -1,0) -
            (1.0/12.0)*OPS_ACC(U1_B0, 2,0)*OPS_ACC(rho_B0, 2,0)*OPS_ACC(detJ_B0, 2,0) + ((1.0/12.0))*OPS_ACC(U1_B0, -2,0)*OPS_ACC(rho_B0, -2,0)*OPS_ACC(detJ_B0, -2,0) +
            ((2.0/3.0))*OPS_ACC(U1_B0, 1,0)*OPS_ACC(rho_B0, 1,0)*OPS_ACC(detJ_B0, 1,0))*invDelta0block0;

   }

   if (idx[1] == 0){

       d1_D00U0detJprhou0_dy = (-3*(OPS_ACC(p_B0, 0,2)*OPS_ACC(D00_B0, 0,2) + OPS_ACC(U0_B0, 0,2)*OPS_ACC(rhou0_B0, 0,2))*OPS_ACC(detJ_B0, 0,2) +
            4*(OPS_ACC(p_B0, 0,1)*OPS_ACC(D00_B0, 0,1) + OPS_ACC(U0_B0, 0,1)*OPS_ACC(rhou0_B0, 0,1))*OPS_ACC(detJ_B0, 0,1) - (25.0/12.0)*(OPS_ACC(p_B0, 0,0)*OPS_ACC(D00_B0, 0,0) +
            OPS_ACC(U0_B0, 0,0)*OPS_ACC(rhou0_B0, 0,0))*OPS_ACC(detJ_B0, 0,0) - (1.0/4.0)*(OPS_ACC(p_B0, 0,4)*OPS_ACC(D00_B0, 0,4) +
            OPS_ACC(U0_B0, 0,4)*OPS_ACC(rhou0_B0, 0,4))*OPS_ACC(detJ_B0, 0,4) + ((4.0/3.0))*(OPS_ACC(p_B0, 0,3)*OPS_ACC(D00_B0, 0,3) +
            OPS_ACC(U0_B0, 0,3)*OPS_ACC(rhou0_B0, 0,3))*OPS_ACC(detJ_B0, 0,3))*invDelta1block0;

       d1_D01U0detJprhou1_dy = (-3*(OPS_ACC(p_B0, 0,2)*OPS_ACC(D01_B0, 0,2) + OPS_ACC(U0_B0, 0,2)*OPS_ACC(rhou1_B0, 0,2))*OPS_ACC(detJ_B0, 0,2) +
            4*(OPS_ACC(p_B0, 0,1)*OPS_ACC(D01_B0, 0,1) + OPS_ACC(U0_B0, 0,1)*OPS_ACC(rhou1_B0, 0,1))*OPS_ACC(detJ_B0, 0,1) - (25.0/12.0)*(OPS_ACC(p_B0, 0,0)*OPS_ACC(D01_B0, 0,0) +
            OPS_ACC(U0_B0, 0,0)*OPS_ACC(rhou1_B0, 0,0))*OPS_ACC(detJ_B0, 0,0) - (1.0/4.0)*(OPS_ACC(p_B0, 0,4)*OPS_ACC(D01_B0, 0,4) +
            OPS_ACC(U0_B0, 0,4)*OPS_ACC(rhou1_B0, 0,4))*OPS_ACC(detJ_B0, 0,4) + ((4.0/3.0))*(OPS_ACC(p_B0, 0,3)*OPS_ACC(D01_B0, 0,3) +
            OPS_ACC(U0_B0, 0,3)*OPS_ACC(rhou1_B0, 0,3))*OPS_ACC(detJ_B0, 0,3))*invDelta1block0;

       d1_D10U1detJprhou0_dy = (-3*(OPS_ACC(p_B0, 0,2)*OPS_ACC(D10_B0, 0,2) + OPS_ACC(U1_B0, 0,2)*OPS_ACC(rhou0_B0, 0,2))*OPS_ACC(detJ_B0, 0,2) +
            4*(OPS_ACC(p_B0, 0,1)*OPS_ACC(D10_B0, 0,1) + OPS_ACC(U1_B0, 0,1)*OPS_ACC(rhou0_B0, 0,1))*OPS_ACC(detJ_B0, 0,1) - (25.0/12.0)*(OPS_ACC(p_B0, 0,0)*OPS_ACC(D10_B0, 0,0) +
            OPS_ACC(U1_B0, 0,0)*OPS_ACC(rhou0_B0, 0,0))*OPS_ACC(detJ_B0, 0,0) - (1.0/4.0)*(OPS_ACC(p_B0, 0,4)*OPS_ACC(D10_B0, 0,4) +
            OPS_ACC(U1_B0, 0,4)*OPS_ACC(rhou0_B0, 0,4))*OPS_ACC(detJ_B0, 0,4) + ((4.0/3.0))*(OPS_ACC(p_B0, 0,3)*OPS_ACC(D10_B0, 0,3) +
            OPS_ACC(U1_B0, 0,3)*OPS_ACC(rhou0_B0, 0,3))*OPS_ACC(detJ_B0, 0,3))*invDelta1block0;

       d1_D11U1detJprhou1_dy = (-3*(OPS_ACC(p_B0, 0,2)*OPS_ACC(D11_B0, 0,2) + OPS_ACC(U1_B0, 0,2)*OPS_ACC(rhou1_B0, 0,2))*OPS_ACC(detJ_B0, 0,2) +
            4*(OPS_ACC(p_B0, 0,1)*OPS_ACC(D11_B0, 0,1) + OPS_ACC(U1_B0, 0,1)*OPS_ACC(rhou1_B0, 0,1))*OPS_ACC(detJ_B0, 0,1) - (25.0/12.0)*(OPS_ACC(p_B0, 0,0)*OPS_ACC(D11_B0, 0,0) +
            OPS_ACC(U1_B0, 0,0)*OPS_ACC(rhou1_B0, 0,0))*OPS_ACC(detJ_B0, 0,0) - (1.0/4.0)*(OPS_ACC(p_B0, 0,4)*OPS_ACC(D11_B0, 0,4) +
            OPS_ACC(U1_B0, 0,4)*OPS_ACC(rhou1_B0, 0,4))*OPS_ACC(detJ_B0, 0,4) + ((4.0/3.0))*(OPS_ACC(p_B0, 0,3)*OPS_ACC(D11_B0, 0,3) +
            OPS_ACC(U1_B0, 0,3)*OPS_ACC(rhou1_B0, 0,3))*OPS_ACC(detJ_B0, 0,3))*invDelta1block0;

       d1_U0detJprhoE_dy = (-3*(OPS_ACC(p_B0, 0,2) + OPS_ACC(rhoE_B0, 0,2))*OPS_ACC(U0_B0, 0,2)*OPS_ACC(detJ_B0, 0,2) + 4*(OPS_ACC(p_B0, 0,1) +
            OPS_ACC(rhoE_B0, 0,1))*OPS_ACC(U0_B0, 0,1)*OPS_ACC(detJ_B0, 0,1) - (25.0/12.0)*(OPS_ACC(p_B0, 0,0) + OPS_ACC(rhoE_B0, 0,0))*OPS_ACC(U0_B0, 0,0)*OPS_ACC(detJ_B0, 0,0) -
            (1.0/4.0)*(OPS_ACC(p_B0, 0,4) + OPS_ACC(rhoE_B0, 0,4))*OPS_ACC(U0_B0, 0,4)*OPS_ACC(detJ_B0, 0,4) + ((4.0/3.0))*(OPS_ACC(p_B0, 0,3) +
            OPS_ACC(rhoE_B0, 0,3))*OPS_ACC(U0_B0, 0,3)*OPS_ACC(detJ_B0, 0,3))*invDelta1block0;

       d1_U1detJprhoE_dy = (-3*(OPS_ACC(p_B0, 0,2) + OPS_ACC(rhoE_B0, 0,2))*OPS_ACC(U1_B0, 0,2)*OPS_ACC(detJ_B0, 0,2) + 4*(OPS_ACC(p_B0, 0,1) +
            OPS_ACC(rhoE_B0, 0,1))*OPS_ACC(U1_B0, 0,1)*OPS_ACC(detJ_B0, 0,1) - (25.0/12.0)*(OPS_ACC(p_B0, 0,0) + OPS_ACC(rhoE_B0, 0,0))*OPS_ACC(U1_B0, 0,0)*OPS_ACC(detJ_B0, 0,0) -
            (1.0/4.0)*(OPS_ACC(p_B0, 0,4) + OPS_ACC(rhoE_B0, 0,4))*OPS_ACC(U1_B0, 0,4)*OPS_ACC(detJ_B0, 0,4) + ((4.0/3.0))*(OPS_ACC(p_B0, 0,3) +
            OPS_ACC(rhoE_B0, 0,3))*OPS_ACC(U1_B0, 0,3)*OPS_ACC(detJ_B0, 0,3))*invDelta1block0;

       d1_U0detJrho_dy = (-3*OPS_ACC(U0_B0, 0,2)*OPS_ACC(rho_B0, 0,2)*OPS_ACC(detJ_B0, 0,2) + 4*OPS_ACC(U0_B0, 0,1)*OPS_ACC(rho_B0, 0,1)*OPS_ACC(detJ_B0, 0,1) -
            (25.0/12.0)*OPS_ACC(U0_B0, 0,0)*OPS_ACC(rho_B0, 0,0)*OPS_ACC(detJ_B0, 0,0) - (1.0/4.0)*OPS_ACC(U0_B0, 0,4)*OPS_ACC(rho_B0, 0,4)*OPS_ACC(detJ_B0, 0,4) +
            ((4.0/3.0))*OPS_ACC(U0_B0, 0,3)*OPS_ACC(rho_B0, 0,3)*OPS_ACC(detJ_B0, 0,3))*invDelta1block0;

       d1_U1detJrho_dy = (-3*OPS_ACC(U1_B0, 0,2)*OPS_ACC(rho_B0, 0,2)*OPS_ACC(detJ_B0, 0,2) + 4*OPS_ACC(U1_B0, 0,1)*OPS_ACC(rho_B0, 0,1)*OPS_ACC(detJ_B0, 0,1) -
            (25.0/12.0)*OPS_ACC(U1_B0, 0,0)*OPS_ACC(rho_B0, 0,0)*OPS_ACC(detJ_B0, 0,0) - (1.0/4.0)*OPS_ACC(U1_B0, 0,4)*OPS_ACC(rho_B0, 0,4)*OPS_ACC(detJ_B0, 0,4) +
            ((4.0/3.0))*OPS_ACC(U1_B0, 0,3)*OPS_ACC(rho_B0, 0,3)*OPS_ACC(detJ_B0, 0,3))*invDelta1block0;

   }

   else if (idx[1] == 1){

       d1_D00U0detJprhou0_dy = (-(5.0/6.0)*(OPS_ACC(p_B0, 0,0)*OPS_ACC(D00_B0, 0,0) + OPS_ACC(U0_B0, 0,0)*OPS_ACC(rhou0_B0, 0,0))*OPS_ACC(detJ_B0, 0,0) -
            (1.0/2.0)*(OPS_ACC(p_B0, 0,2)*OPS_ACC(D00_B0, 0,2) + OPS_ACC(U0_B0, 0,2)*OPS_ACC(rhou0_B0, 0,2))*OPS_ACC(detJ_B0, 0,2) -
            (1.0/4.0)*(OPS_ACC(p_B0, 0,-1)*OPS_ACC(D00_B0, 0,-1) + OPS_ACC(U0_B0, 0,-1)*OPS_ACC(rhou0_B0, 0,-1))*OPS_ACC(detJ_B0, 0,-1) +
            ((1.0/12.0))*(OPS_ACC(p_B0, 0,3)*OPS_ACC(D00_B0, 0,3) + OPS_ACC(U0_B0, 0,3)*OPS_ACC(rhou0_B0, 0,3))*OPS_ACC(detJ_B0, 0,3) +
            ((3.0/2.0))*(OPS_ACC(p_B0, 0,1)*OPS_ACC(D00_B0, 0,1) + OPS_ACC(U0_B0, 0,1)*OPS_ACC(rhou0_B0, 0,1))*OPS_ACC(detJ_B0, 0,1))*invDelta1block0;

       d1_D01U0detJprhou1_dy = (-(5.0/6.0)*(OPS_ACC(p_B0, 0,0)*OPS_ACC(D01_B0, 0,0) + OPS_ACC(U0_B0, 0,0)*OPS_ACC(rhou1_B0, 0,0))*OPS_ACC(detJ_B0, 0,0) -
            (1.0/2.0)*(OPS_ACC(p_B0, 0,2)*OPS_ACC(D01_B0, 0,2) + OPS_ACC(U0_B0, 0,2)*OPS_ACC(rhou1_B0, 0,2))*OPS_ACC(detJ_B0, 0,2) -
            (1.0/4.0)*(OPS_ACC(p_B0, 0,-1)*OPS_ACC(D01_B0, 0,-1) + OPS_ACC(U0_B0, 0,-1)*OPS_ACC(rhou1_B0, 0,-1))*OPS_ACC(detJ_B0, 0,-1) +
            ((1.0/12.0))*(OPS_ACC(p_B0, 0,3)*OPS_ACC(D01_B0, 0,3) + OPS_ACC(U0_B0, 0,3)*OPS_ACC(rhou1_B0, 0,3))*OPS_ACC(detJ_B0, 0,3) +
            ((3.0/2.0))*(OPS_ACC(p_B0, 0,1)*OPS_ACC(D01_B0, 0,1) + OPS_ACC(U0_B0, 0,1)*OPS_ACC(rhou1_B0, 0,1))*OPS_ACC(detJ_B0, 0,1))*invDelta1block0;

       d1_D10U1detJprhou0_dy = (-(5.0/6.0)*(OPS_ACC(p_B0, 0,0)*OPS_ACC(D10_B0, 0,0) + OPS_ACC(U1_B0, 0,0)*OPS_ACC(rhou0_B0, 0,0))*OPS_ACC(detJ_B0, 0,0) -
            (1.0/2.0)*(OPS_ACC(p_B0, 0,2)*OPS_ACC(D10_B0, 0,2) + OPS_ACC(U1_B0, 0,2)*OPS_ACC(rhou0_B0, 0,2))*OPS_ACC(detJ_B0, 0,2) -
            (1.0/4.0)*(OPS_ACC(p_B0, 0,-1)*OPS_ACC(D10_B0, 0,-1) + OPS_ACC(U1_B0, 0,-1)*OPS_ACC(rhou0_B0, 0,-1))*OPS_ACC(detJ_B0, 0,-1) +
            ((1.0/12.0))*(OPS_ACC(p_B0, 0,3)*OPS_ACC(D10_B0, 0,3) + OPS_ACC(U1_B0, 0,3)*OPS_ACC(rhou0_B0, 0,3))*OPS_ACC(detJ_B0, 0,3) +
            ((3.0/2.0))*(OPS_ACC(p_B0, 0,1)*OPS_ACC(D10_B0, 0,1) + OPS_ACC(U1_B0, 0,1)*OPS_ACC(rhou0_B0, 0,1))*OPS_ACC(detJ_B0, 0,1))*invDelta1block0;

       d1_D11U1detJprhou1_dy = (-(5.0/6.0)*(OPS_ACC(p_B0, 0,0)*OPS_ACC(D11_B0, 0,0) + OPS_ACC(U1_B0, 0,0)*OPS_ACC(rhou1_B0, 0,0))*OPS_ACC(detJ_B0, 0,0) -
            (1.0/2.0)*(OPS_ACC(p_B0, 0,2)*OPS_ACC(D11_B0, 0,2) + OPS_ACC(U1_B0, 0,2)*OPS_ACC(rhou1_B0, 0,2))*OPS_ACC(detJ_B0, 0,2) -
            (1.0/4.0)*(OPS_ACC(p_B0, 0,-1)*OPS_ACC(D11_B0, 0,-1) + OPS_ACC(U1_B0, 0,-1)*OPS_ACC(rhou1_B0, 0,-1))*OPS_ACC(detJ_B0, 0,-1) +
            ((1.0/12.0))*(OPS_ACC(p_B0, 0,3)*OPS_ACC(D11_B0, 0,3) + OPS_ACC(U1_B0, 0,3)*OPS_ACC(rhou1_B0, 0,3))*OPS_ACC(detJ_B0, 0,3) +
            ((3.0/2.0))*(OPS_ACC(p_B0, 0,1)*OPS_ACC(D11_B0, 0,1) + OPS_ACC(U1_B0, 0,1)*OPS_ACC(rhou1_B0, 0,1))*OPS_ACC(detJ_B0, 0,1))*invDelta1block0;

       d1_U0detJprhoE_dy = (-(5.0/6.0)*(OPS_ACC(p_B0, 0,0) + OPS_ACC(rhoE_B0, 0,0))*OPS_ACC(U0_B0, 0,0)*OPS_ACC(detJ_B0, 0,0) - (1.0/2.0)*(OPS_ACC(p_B0, 0,2) +
            OPS_ACC(rhoE_B0, 0,2))*OPS_ACC(U0_B0, 0,2)*OPS_ACC(detJ_B0, 0,2) - (1.0/4.0)*(OPS_ACC(p_B0, 0,-1) + OPS_ACC(rhoE_B0, 0,-1))*OPS_ACC(U0_B0, 0,-1)*OPS_ACC(detJ_B0, 0,-1) +
            ((1.0/12.0))*(OPS_ACC(p_B0, 0,3) + OPS_ACC(rhoE_B0, 0,3))*OPS_ACC(U0_B0, 0,3)*OPS_ACC(detJ_B0, 0,3) + ((3.0/2.0))*(OPS_ACC(p_B0, 0,1) +
            OPS_ACC(rhoE_B0, 0,1))*OPS_ACC(U0_B0, 0,1)*OPS_ACC(detJ_B0, 0,1))*invDelta1block0;

       d1_U1detJprhoE_dy = (-(5.0/6.0)*(OPS_ACC(p_B0, 0,0) + OPS_ACC(rhoE_B0, 0,0))*OPS_ACC(U1_B0, 0,0)*OPS_ACC(detJ_B0, 0,0) - (1.0/2.0)*(OPS_ACC(p_B0, 0,2) +
            OPS_ACC(rhoE_B0, 0,2))*OPS_ACC(U1_B0, 0,2)*OPS_ACC(detJ_B0, 0,2) - (1.0/4.0)*(OPS_ACC(p_B0, 0,-1) + OPS_ACC(rhoE_B0, 0,-1))*OPS_ACC(U1_B0, 0,-1)*OPS_ACC(detJ_B0, 0,-1) +
            ((1.0/12.0))*(OPS_ACC(p_B0, 0,3) + OPS_ACC(rhoE_B0, 0,3))*OPS_ACC(U1_B0, 0,3)*OPS_ACC(detJ_B0, 0,3) + ((3.0/2.0))*(OPS_ACC(p_B0, 0,1) +
            OPS_ACC(rhoE_B0, 0,1))*OPS_ACC(U1_B0, 0,1)*OPS_ACC(detJ_B0, 0,1))*invDelta1block0;

       d1_U0detJrho_dy = (-(5.0/6.0)*OPS_ACC(U0_B0, 0,0)*OPS_ACC(rho_B0, 0,0)*OPS_ACC(detJ_B0, 0,0) - (1.0/2.0)*OPS_ACC(U0_B0, 0,2)*OPS_ACC(rho_B0, 0,2)*OPS_ACC(detJ_B0, 0,2)
            - (1.0/4.0)*OPS_ACC(U0_B0, 0,-1)*OPS_ACC(rho_B0, 0,-1)*OPS_ACC(detJ_B0, 0,-1) + ((1.0/12.0))*OPS_ACC(U0_B0, 0,3)*OPS_ACC(rho_B0, 0,3)*OPS_ACC(detJ_B0, 0,3) +
            ((3.0/2.0))*OPS_ACC(U0_B0, 0,1)*OPS_ACC(rho_B0, 0,1)*OPS_ACC(detJ_B0, 0,1))*invDelta1block0;

       d1_U1detJrho_dy = (-(5.0/6.0)*OPS_ACC(U1_B0, 0,0)*OPS_ACC(rho_B0, 0,0)*OPS_ACC(detJ_B0, 0,0) - (1.0/2.0)*OPS_ACC(U1_B0, 0,2)*OPS_ACC(rho_B0, 0,2)*OPS_ACC(detJ_B0, 0,2)
            - (1.0/4.0)*OPS_ACC(U1_B0, 0,-1)*OPS_ACC(rho_B0, 0,-1)*OPS_ACC(detJ_B0, 0,-1) + ((1.0/12.0))*OPS_ACC(U1_B0, 0,3)*OPS_ACC(rho_B0, 0,3)*OPS_ACC(detJ_B0, 0,3) +
            ((3.0/2.0))*OPS_ACC(U1_B0, 0,1)*OPS_ACC(rho_B0, 0,1)*OPS_ACC(detJ_B0, 0,1))*invDelta1block0;

   }

   else{

       d1_D00U0detJprhou0_dy = (-(2.0/3.0)*(OPS_ACC(p_B0, 0,-1)*OPS_ACC(D00_B0, 0,-1) + OPS_ACC(U0_B0, 0,-1)*OPS_ACC(rhou0_B0, 0,-1))*OPS_ACC(detJ_B0, 0,-1) -
            (1.0/12.0)*(OPS_ACC(p_B0, 0,2)*OPS_ACC(D00_B0, 0,2) + OPS_ACC(U0_B0, 0,2)*OPS_ACC(rhou0_B0, 0,2))*OPS_ACC(detJ_B0, 0,2) +
            ((1.0/12.0))*(OPS_ACC(p_B0, 0,-2)*OPS_ACC(D00_B0, 0,-2) + OPS_ACC(U0_B0, 0,-2)*OPS_ACC(rhou0_B0, 0,-2))*OPS_ACC(detJ_B0, 0,-2) +
            ((2.0/3.0))*(OPS_ACC(p_B0, 0,1)*OPS_ACC(D00_B0, 0,1) + OPS_ACC(U0_B0, 0,1)*OPS_ACC(rhou0_B0, 0,1))*OPS_ACC(detJ_B0, 0,1))*invDelta1block0;

       d1_D01U0detJprhou1_dy = (-(2.0/3.0)*(OPS_ACC(p_B0, 0,-1)*OPS_ACC(D01_B0, 0,-1) + OPS_ACC(U0_B0, 0,-1)*OPS_ACC(rhou1_B0, 0,-1))*OPS_ACC(detJ_B0, 0,-1) -
            (1.0/12.0)*(OPS_ACC(p_B0, 0,2)*OPS_ACC(D01_B0, 0,2) + OPS_ACC(U0_B0, 0,2)*OPS_ACC(rhou1_B0, 0,2))*OPS_ACC(detJ_B0, 0,2) +
            ((1.0/12.0))*(OPS_ACC(p_B0, 0,-2)*OPS_ACC(D01_B0, 0,-2) + OPS_ACC(U0_B0, 0,-2)*OPS_ACC(rhou1_B0, 0,-2))*OPS_ACC(detJ_B0, 0,-2) +
            ((2.0/3.0))*(OPS_ACC(p_B0, 0,1)*OPS_ACC(D01_B0, 0,1) + OPS_ACC(U0_B0, 0,1)*OPS_ACC(rhou1_B0, 0,1))*OPS_ACC(detJ_B0, 0,1))*invDelta1block0;

       d1_D10U1detJprhou0_dy = (-(2.0/3.0)*(OPS_ACC(p_B0, 0,-1)*OPS_ACC(D10_B0, 0,-1) + OPS_ACC(U1_B0, 0,-1)*OPS_ACC(rhou0_B0, 0,-1))*OPS_ACC(detJ_B0, 0,-1) -
            (1.0/12.0)*(OPS_ACC(p_B0, 0,2)*OPS_ACC(D10_B0, 0,2) + OPS_ACC(U1_B0, 0,2)*OPS_ACC(rhou0_B0, 0,2))*OPS_ACC(detJ_B0, 0,2) +
            ((1.0/12.0))*(OPS_ACC(p_B0, 0,-2)*OPS_ACC(D10_B0, 0,-2) + OPS_ACC(U1_B0, 0,-2)*OPS_ACC(rhou0_B0, 0,-2))*OPS_ACC(detJ_B0, 0,-2) +
            ((2.0/3.0))*(OPS_ACC(p_B0, 0,1)*OPS_ACC(D10_B0, 0,1) + OPS_ACC(U1_B0, 0,1)*OPS_ACC(rhou0_B0, 0,1))*OPS_ACC(detJ_B0, 0,1))*invDelta1block0;

       d1_D11U1detJprhou1_dy = (-(2.0/3.0)*(OPS_ACC(p_B0, 0,-1)*OPS_ACC(D11_B0, 0,-1) + OPS_ACC(U1_B0, 0,-1)*OPS_ACC(rhou1_B0, 0,-1))*OPS_ACC(detJ_B0, 0,-1) -
            (1.0/12.0)*(OPS_ACC(p_B0, 0,2)*OPS_ACC(D11_B0, 0,2) + OPS_ACC(U1_B0, 0,2)*OPS_ACC(rhou1_B0, 0,2))*OPS_ACC(detJ_B0, 0,2) +
            ((1.0/12.0))*(OPS_ACC(p_B0, 0,-2)*OPS_ACC(D11_B0, 0,-2) + OPS_ACC(U1_B0, 0,-2)*OPS_ACC(rhou1_B0, 0,-2))*OPS_ACC(detJ_B0, 0,-2) +
            ((2.0/3.0))*(OPS_ACC(p_B0, 0,1)*OPS_ACC(D11_B0, 0,1) + OPS_ACC(U1_B0, 0,1)*OPS_ACC(rhou1_B0, 0,1))*OPS_ACC(detJ_B0, 0,1))*invDelta1block0;

       d1_U0detJprhoE_dy = (-(2.0/3.0)*(OPS_ACC(p_B0, 0,-1) + OPS_ACC(rhoE_B0, 0,-1))*OPS_ACC(U0_B0, 0,-1)*OPS_ACC(detJ_B0, 0,-1) - (1.0/12.0)*(OPS_ACC(p_B0, 0,2) +
            OPS_ACC(rhoE_B0, 0,2))*OPS_ACC(U0_B0, 0,2)*OPS_ACC(detJ_B0, 0,2) + ((1.0/12.0))*(OPS_ACC(p_B0, 0,-2) + OPS_ACC(rhoE_B0, 0,-2))*OPS_ACC(U0_B0, 0,-2)*OPS_ACC(detJ_B0, 0,-2)
            + ((2.0/3.0))*(OPS_ACC(p_B0, 0,1) + OPS_ACC(rhoE_B0, 0,1))*OPS_ACC(U0_B0, 0,1)*OPS_ACC(detJ_B0, 0,1))*invDelta1block0;

       d1_U1detJprhoE_dy = (-(2.0/3.0)*(OPS_ACC(p_B0, 0,-1) + OPS_ACC(rhoE_B0, 0,-1))*OPS_ACC(U1_B0, 0,-1)*OPS_ACC(detJ_B0, 0,-1) - (1.0/12.0)*(OPS_ACC(p_B0, 0,2) +
            OPS_ACC(rhoE_B0, 0,2))*OPS_ACC(U1_B0, 0,2)*OPS_ACC(detJ_B0, 0,2) + ((1.0/12.0))*(OPS_ACC(p_B0, 0,-2) + OPS_ACC(rhoE_B0, 0,-2))*OPS_ACC(U1_B0, 0,-2)*OPS_ACC(detJ_B0, 0,-2)
            + ((2.0/3.0))*(OPS_ACC(p_B0, 0,1) + OPS_ACC(rhoE_B0, 0,1))*OPS_ACC(U1_B0, 0,1)*OPS_ACC(detJ_B0, 0,1))*invDelta1block0;

       d1_U0detJrho_dy = (-(2.0/3.0)*OPS_ACC(U0_B0, 0,-1)*OPS_ACC(rho_B0, 0,-1)*OPS_ACC(detJ_B0, 0,-1) -
            (1.0/12.0)*OPS_ACC(U0_B0, 0,2)*OPS_ACC(rho_B0, 0,2)*OPS_ACC(detJ_B0, 0,2) + ((1.0/12.0))*OPS_ACC(U0_B0, 0,-2)*OPS_ACC(rho_B0, 0,-2)*OPS_ACC(detJ_B0, 0,-2) +
            ((2.0/3.0))*OPS_ACC(U0_B0, 0,1)*OPS_ACC(rho_B0, 0,1)*OPS_ACC(detJ_B0, 0,1))*invDelta1block0;

       d1_U1detJrho_dy = (-(2.0/3.0)*OPS_ACC(U1_B0, 0,-1)*OPS_ACC(rho_B0, 0,-1)*OPS_ACC(detJ_B0, 0,-1) -
            (1.0/12.0)*OPS_ACC(U1_B0, 0,2)*OPS_ACC(rho_B0, 0,2)*OPS_ACC(detJ_B0, 0,2) + ((1.0/12.0))*OPS_ACC(U1_B0, 0,-2)*OPS_ACC(rho_B0, 0,-2)*OPS_ACC(detJ_B0, 0,-2) +
            ((2.0/3.0))*OPS_ACC(U1_B0, 0,1)*OPS_ACC(rho_B0, 0,1)*OPS_ACC(detJ_B0, 0,1))*invDelta1block0;

   }

    OPS_ACC(Residual0_B0, 0,0) = -(OPS_ACC(D00_B0, 0,0)*d1_U0detJrho_dx + OPS_ACC(D01_B0, 0,0)*d1_U1detJrho_dx + OPS_ACC(D10_B0, 0,0)*d1_U0detJrho_dy +
      OPS_ACC(D11_B0, 0,0)*d1_U1detJrho_dy)/OPS_ACC(detJ_B0, 0,0);

    OPS_ACC(Residual1_B0, 0,0) = -(OPS_ACC(D00_B0, 0,0)*d1_D00U0detJprhou0_dx + OPS_ACC(D01_B0, 0,0)*d1_D10U1detJprhou0_dx +
      OPS_ACC(D10_B0, 0,0)*d1_D00U0detJprhou0_dy + OPS_ACC(D11_B0, 0,0)*d1_D10U1detJprhou0_dy)/OPS_ACC(detJ_B0, 0,0);

    OPS_ACC(Residual2_B0, 0,0) = -(OPS_ACC(D00_B0, 0,0)*d1_D01U0detJprhou1_dx + OPS_ACC(D01_B0, 0,0)*d1_D11U1detJprhou1_dx +
      OPS_ACC(D10_B0, 0,0)*d1_D01U0detJprhou1_dy + OPS_ACC(D11_B0, 0,0)*d1_D11U1detJprhou1_dy)/OPS_ACC(detJ_B0, 0,0);

    OPS_ACC(Residual3_B0, 0,0) = -(OPS_ACC(D00_B0, 0,0)*d1_U0detJprhoE_dx + OPS_ACC(D01_B0, 0,0)*d1_U1detJprhoE_dx + OPS_ACC(D10_B0, 0,0)*d1_U0detJprhoE_dy
      + OPS_ACC(D11_B0, 0,0)*d1_U1detJprhoE_dy)/OPS_ACC(detJ_B0, 0,0);


    }
  }
}
