//
// auto-generated by ops.py//

#include "./OpenACC/opensbli_common.h"

#include <openacc.h>

void ops_init_backend() {acc_set_device_num(ops_get_proc()%acc_get_num_devices(acc_device_nvidia),acc_device_nvidia); }

void ops_decl_const_char(int dim, char const *type,
int size, char *dat, char const *name){
  ops_execute(OPS_instance::getOPSInstance());
  if (!strcmp(name,"Delta0block0")) {
    Delta0block0 = *(double*)dat;
  }
  else
  if (!strcmp(name,"Delta1block0")) {
    Delta1block0 = *(double*)dat;
  }
  else
  if (!strcmp(name,"HDF5_timing")) {
    HDF5_timing = *(int*)dat;
  }
  else
  if (!strcmp(name,"Lx1")) {
    Lx1 = *(double*)dat;
  }
  else
  if (!strcmp(name,"Minf")) {
    Minf = *(double*)dat;
  }
  else
  if (!strcmp(name,"Pr")) {
    Pr = *(double*)dat;
  }
  else
  if (!strcmp(name,"Re")) {
    Re = *(double*)dat;
  }
  else
  if (!strcmp(name,"RefT")) {
    RefT = *(double*)dat;
  }
  else
  if (!strcmp(name,"SuthT")) {
    SuthT = *(double*)dat;
  }
  else
  if (!strcmp(name,"TENO_CT")) {
    TENO_CT = *(double*)dat;
  }
  else
  if (!strcmp(name,"Twall")) {
    Twall = *(double*)dat;
  }
  else
  if (!strcmp(name,"block0np0")) {
    block0np0 = *(int*)dat;
  }
  else
  if (!strcmp(name,"block0np1")) {
    block0np1 = *(int*)dat;
  }
  else
  if (!strcmp(name,"by")) {
    by = *(double*)dat;
  }
  else
  if (!strcmp(name,"dt")) {
    dt = *(double*)dat;
  }
  else
  if (!strcmp(name,"eps")) {
    eps = *(double*)dat;
  }
  else
  if (!strcmp(name,"gama")) {
    gama = *(double*)dat;
  }
  else
  if (!strcmp(name,"gamma_m1")) {
    gamma_m1 = *(double*)dat;
  }
  else
  if (!strcmp(name,"inv2Delta0block0")) {
    inv2Delta0block0 = *(double*)dat;
  }
  else
  if (!strcmp(name,"inv2Delta1block0")) {
    inv2Delta1block0 = *(double*)dat;
  }
  else
  if (!strcmp(name,"inv2Minf")) {
    inv2Minf = *(double*)dat;
  }
  else
  if (!strcmp(name,"invDelta0block0")) {
    invDelta0block0 = *(double*)dat;
  }
  else
  if (!strcmp(name,"invDelta1block0")) {
    invDelta1block0 = *(double*)dat;
  }
  else
  if (!strcmp(name,"invLx1")) {
    invLx1 = *(double*)dat;
  }
  else
  if (!strcmp(name,"invPr")) {
    invPr = *(double*)dat;
  }
  else
  if (!strcmp(name,"invRe")) {
    invRe = *(double*)dat;
  }
  else
  if (!strcmp(name,"invRefT")) {
    invRefT = *(double*)dat;
  }
  else
  if (!strcmp(name,"inv_gamma_m1")) {
    inv_gamma_m1 = *(double*)dat;
  }
  else
  if (!strcmp(name,"invgama")) {
    invgama = *(double*)dat;
  }
  else
  if (!strcmp(name,"invgamma_m1")) {
    invgamma_m1 = *(double*)dat;
  }
  else
  if (!strcmp(name,"niter")) {
    niter = *(int*)dat;
  }
  else
  if (!strcmp(name,"shock_filter_control")) {
    shock_filter_control = *(double*)dat;
  }
  else
  if (!strcmp(name,"simulation_time")) {
    simulation_time = *(double*)dat;
  }
  else
  if (!strcmp(name,"start_iter")) {
    start_iter = *(int*)dat;
  }
  else
  if (!strcmp(name,"write_output_file")) {
    write_output_file = *(int*)dat;
  }
  else
  {
    throw OPSException(OPS_RUNTIME_ERROR, "error: unknown const name");
  }
}

//user kernel files
#include "opensbliblock00Kernel052_openacc_kernel.cpp"
#include "opensbliblock00Kernel055_openacc_kernel.cpp"
#include "opensbliblock00Kernel056_openacc_kernel.cpp"
#include "opensbliblock00Kernel057_openacc_kernel.cpp"
#include "opensbliblock00Kernel058_openacc_kernel.cpp"
#include "opensbliblock00Kernel059_openacc_kernel.cpp"
#include "opensbliblock00Kernel064_openacc_kernel.cpp"
#include "opensbliblock00Kernel048_openacc_kernel.cpp"
#include "opensbliblock00Kernel049_openacc_kernel.cpp"
#include "opensbliblock00Kernel050_openacc_kernel.cpp"
#include "opensbliblock00Kernel051_openacc_kernel.cpp"
#include "opensbliblock00Kernel003_openacc_kernel.cpp"
#include "opensbliblock00Kernel005_openacc_kernel.cpp"
#include "opensbliblock00Kernel012_openacc_kernel.cpp"
#include "opensbliblock00Kernel013_openacc_kernel.cpp"
#include "opensbliblock00Kernel014_openacc_kernel.cpp"
#include "opensbliblock00Kernel008_openacc_kernel.cpp"
#include "opensbliblock00Kernel021_openacc_kernel.cpp"
#include "opensbliblock00Kernel025_openacc_kernel.cpp"
#include "opensbliblock00Kernel000_openacc_kernel.cpp"
#include "opensbliblock00Kernel001_openacc_kernel.cpp"
#include "opensbliblock00Kernel017_openacc_kernel.cpp"
#include "opensbliblock00Kernel028_openacc_kernel.cpp"
#include "opensbliblock00Kernel030_openacc_kernel.cpp"
#include "opensbliblock00Kernel032_openacc_kernel.cpp"
#include "opensbliblock00Kernel034_openacc_kernel.cpp"
#include "opensbliblock00Kernel036_openacc_kernel.cpp"
#include "opensbliblock00Kernel037_openacc_kernel.cpp"
#include "opensbliblock00Kernel038_openacc_kernel.cpp"
#include "opensbliblock00Kernel039_openacc_kernel.cpp"
#include "opensbliblock00Kernel044_openacc_kernel.cpp"
#include "opensbliblock00Kernel065_openacc_kernel.cpp"
