//
// auto-generated by ops.py//

//header
#define OPS_2D
#define OPS_API 2
#include "ops_lib_core.h"
#ifdef OPS_MPI
#include "ops_mpi_core.h"
#endif

// global constants
extern double Delta0block0;
extern double Delta1block0;
extern int HDF5_timing;
extern double Lx1;
extern double Minf;
extern double Pr;
extern double Re;
extern double RefT;
extern double SuthT;
extern double TENO_CT;
extern double Twall;
extern int block0np0;
extern int block0np1;
extern double by;
extern double dt;
extern double eps;
extern double gama;
extern double gamma_m1;
extern double inv2Delta0block0;
extern double inv2Delta1block0;
extern double inv2Minf;
extern double invDelta0block0;
extern double invDelta1block0;
extern double invLx1;
extern double invPr;
extern double invRe;
extern double invRefT;
extern double inv_gamma_m1;
extern double invgama;
extern double invgamma_m1;
extern int niter;
extern double shock_filter_control;
extern double simulation_time;
extern int start_iter;
extern int write_output_file;

void ops_init_backend() {}

//user kernel files
#include "opensbliblock00Kernel052_cpu_kernel.cpp"
#include "opensbliblock00Kernel055_cpu_kernel.cpp"
#include "opensbliblock00Kernel056_cpu_kernel.cpp"
#include "opensbliblock00Kernel057_cpu_kernel.cpp"
#include "opensbliblock00Kernel058_cpu_kernel.cpp"
#include "opensbliblock00Kernel059_cpu_kernel.cpp"
#include "opensbliblock00Kernel064_cpu_kernel.cpp"
#include "opensbliblock00Kernel048_cpu_kernel.cpp"
#include "opensbliblock00Kernel049_cpu_kernel.cpp"
#include "opensbliblock00Kernel050_cpu_kernel.cpp"
#include "opensbliblock00Kernel051_cpu_kernel.cpp"
#include "opensbliblock00Kernel003_cpu_kernel.cpp"
#include "opensbliblock00Kernel005_cpu_kernel.cpp"
#include "opensbliblock00Kernel012_cpu_kernel.cpp"
#include "opensbliblock00Kernel013_cpu_kernel.cpp"
#include "opensbliblock00Kernel014_cpu_kernel.cpp"
#include "opensbliblock00Kernel008_cpu_kernel.cpp"
#include "opensbliblock00Kernel021_cpu_kernel.cpp"
#include "opensbliblock00Kernel025_cpu_kernel.cpp"
#include "opensbliblock00Kernel000_cpu_kernel.cpp"
#include "opensbliblock00Kernel001_cpu_kernel.cpp"
#include "opensbliblock00Kernel017_cpu_kernel.cpp"
#include "opensbliblock00Kernel028_cpu_kernel.cpp"
#include "opensbliblock00Kernel030_cpu_kernel.cpp"
#include "opensbliblock00Kernel032_cpu_kernel.cpp"
#include "opensbliblock00Kernel034_cpu_kernel.cpp"
#include "opensbliblock00Kernel036_cpu_kernel.cpp"
#include "opensbliblock00Kernel037_cpu_kernel.cpp"
#include "opensbliblock00Kernel038_cpu_kernel.cpp"
#include "opensbliblock00Kernel039_cpu_kernel.cpp"
#include "opensbliblock00Kernel044_cpu_kernel.cpp"
#include "opensbliblock00Kernel065_cpu_kernel.cpp"
