//
// auto-generated by ops.py
//

#include "./MPI_inline/opensbli_common.h"


void ops_init_backend() {}

void ops_decl_const_char2(int dim, char const *type,
int size, char *dat, char const *name){
  if (!strcmp(name,"Delta0block0")) {
    Delta0block0 = *(double*)dat;
  }
  else
  if (!strcmp(name,"Delta1block0")) {
    Delta1block0 = *(double*)dat;
  }
  else
  if (!strcmp(name,"HDF5_timing")) {
    HDF5_timing = *(int*)dat;
  }
  else
  if (!strcmp(name,"Minf")) {
    Minf = *(double*)dat;
  }
  else
  if (!strcmp(name,"Pr")) {
    Pr = *(double*)dat;
  }
  else
  if (!strcmp(name,"Re")) {
    Re = *(double*)dat;
  }
  else
  if (!strcmp(name,"RefT")) {
    RefT = *(double*)dat;
  }
  else
  if (!strcmp(name,"Rhat")) {
    Rhat = *(double*)dat;
  }
  else
  if (!strcmp(name,"SuthT")) {
    SuthT = *(double*)dat;
  }
  else
  if (!strcmp(name,"Twall")) {
    Twall = *(double*)dat;
  }
  else
  if (!strcmp(name,"block0np0")) {
    block0np0 = *(int*)dat;
  }
  else
  if (!strcmp(name,"block0np1")) {
    block0np1 = *(int*)dat;
  }
  else
  if (!strcmp(name,"dt")) {
    dt = *(double*)dat;
  }
  else
  if (!strcmp(name,"gama")) {
    gama = *(double*)dat;
  }
  else
  if (!strcmp(name,"inv2Delta0block0")) {
    inv2Delta0block0 = *(double*)dat;
  }
  else
  if (!strcmp(name,"inv2Delta1block0")) {
    inv2Delta1block0 = *(double*)dat;
  }
  else
  if (!strcmp(name,"inv2Minf")) {
    inv2Minf = *(double*)dat;
  }
  else
  if (!strcmp(name,"invDelta0block0")) {
    invDelta0block0 = *(double*)dat;
  }
  else
  if (!strcmp(name,"invDelta1block0")) {
    invDelta1block0 = *(double*)dat;
  }
  else
  if (!strcmp(name,"invPr")) {
    invPr = *(double*)dat;
  }
  else
  if (!strcmp(name,"invRe")) {
    invRe = *(double*)dat;
  }
  else
  if (!strcmp(name,"invRefT")) {
    invRefT = *(double*)dat;
  }
  else
  if (!strcmp(name,"invRhat")) {
    invRhat = *(double*)dat;
  }
  else
  if (!strcmp(name,"inv_gamma_m1")) {
    inv_gamma_m1 = *(double*)dat;
  }
  else
  if (!strcmp(name,"invgama")) {
    invgama = *(double*)dat;
  }
  else
  if (!strcmp(name,"niter")) {
    niter = *(int*)dat;
  }
  else
  if (!strcmp(name,"pref")) {
    pref = *(double*)dat;
  }
  else
  if (!strcmp(name,"simulation_time")) {
    simulation_time = *(double*)dat;
  }
  else
  if (!strcmp(name,"start_iter")) {
    start_iter = *(int*)dat;
  }
  else
  if (!strcmp(name,"write_output_file")) {
    write_output_file = *(int*)dat;
  }
  else
  {
    throw OPSException(OPS_RUNTIME_ERROR, "error: unknown const name");
  }
}

//user kernel files
#include "opensbliblock00Kernel026_mpiinline_kernel.cpp"
#include "opensbliblock00Kernel029_mpiinline_kernel.cpp"
#include "opensbliblock00Kernel030_mpiinline_kernel.cpp"
#include "opensbliblock00Kernel031_mpiinline_kernel.cpp"
#include "opensbliblock00Kernel032_mpiinline_kernel.cpp"
#include "opensbliblock00Kernel033_mpiinline_kernel.cpp"
#include "opensbliblock00Kernel038_mpiinline_kernel.cpp"
#include "opensbliblock00Kernel022_mpiinline_kernel.cpp"
#include "opensbliblock00Kernel023_mpiinline_kernel.cpp"
#include "opensbliblock00Kernel024_mpiinline_kernel.cpp"
#include "opensbliblock00Kernel025_mpiinline_kernel.cpp"
#include "opensbliblock00Kernel001_mpiinline_kernel.cpp"
#include "opensbliblock00Kernel003_mpiinline_kernel.cpp"
#include "opensbliblock00Kernel012_mpiinline_kernel.cpp"
#include "opensbliblock00Kernel007_mpiinline_kernel.cpp"
#include "opensbliblock00Kernel016_mpiinline_kernel.cpp"
#include "opensbliblock00Kernel000_mpiinline_kernel.cpp"
#include "opensbliblock00Kernel002_mpiinline_kernel.cpp"
#include "opensbliblock00Kernel004_mpiinline_kernel.cpp"
#include "opensbliblock00Kernel006_mpiinline_kernel.cpp"
#include "opensbliblock00Kernel008_mpiinline_kernel.cpp"
#include "opensbliblock00Kernel009_mpiinline_kernel.cpp"
#include "opensbliblock00Kernel010_mpiinline_kernel.cpp"
#include "opensbliblock00Kernel011_mpiinline_kernel.cpp"
#include "opensbliblock00Kernel020_mpiinline_kernel.cpp"
#include "opensbliblock00Kernel021_mpiinline_kernel.cpp"
#include "opensbliblock00Kernel039_mpiinline_kernel.cpp"
